// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_logs.sql

package dbmodel

import (
	"context"
	"database/sql"
)

const createCustomerLog = `-- name: CreateCustomerLog :exec
INSERT INTO customer_logs (
  customer_username,
  log_type
) VALUES (
  ?, ?
)
`

type CreateCustomerLogParams struct {
	CustomerUsername sql.NullString      `json:"customerUsername"`
	LogType          CustomerLogsLogType `json:"logType"`
}

func (q *Queries) CreateCustomerLog(ctx context.Context, arg CreateCustomerLogParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerLog, arg.CustomerUsername, arg.LogType)
	return err
}
