// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package dbmodel

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO
  customers (
    username,
    health_info,
    address,
    company_name,
    company_position,
    marital_status,
    emergency_contact_name,
    emergency_contact_relationship,
    emergency_contact_phone,
    marketing_source
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

func (q *Queries) CreateCustomer(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createCustomer)
	return err
}
