// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_durations.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const createCustomerDuration = `-- name: CreateCustomerDuration :exec
INSERT INTO customer_durations (
  customer_username,
  sales_username,
  product_id,
  purchase_date,
  start_date,
  end_date,
  price_paid,
  discount_amount,
  status
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateCustomerDurationParams struct {
	CustomerUsername sql.NullString          `json:"customerUsername"`
	SalesUsername    sql.NullString          `json:"salesUsername"`
	ProductID        sql.NullInt32           `json:"productId"`
	PurchaseDate     time.Time               `json:"purchaseDate"`
	StartDate        time.Time               `json:"startDate"`
	EndDate          time.Time               `json:"endDate"`
	PricePaid        string                  `json:"pricePaid"`
	DiscountAmount   sql.NullString          `json:"discountAmount"`
	Status           CustomerDurationsStatus `json:"status"`
}

func (q *Queries) CreateCustomerDuration(ctx context.Context, arg CreateCustomerDurationParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerDuration,
		arg.CustomerUsername,
		arg.SalesUsername,
		arg.ProductID,
		arg.PurchaseDate,
		arg.StartDate,
		arg.EndDate,
		arg.PricePaid,
		arg.DiscountAmount,
		arg.Status,
	)
	return err
}

const getCustomerDurationById = `-- name: GetCustomerDurationById :one
SELECT
  id,
  customer_username,
  sales_username,
  product_id,
  purchase_date,
  start_date,
  end_date,
  price_paid,
  discount_amount,
  status,
  created_at,
  updated_at
FROM customer_durations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCustomerDurationById(ctx context.Context, id int32) (CustomerDuration, error) {
	row := q.db.QueryRowContext(ctx, getCustomerDurationById, id)
	var i CustomerDuration
	err := row.Scan(
		&i.ID,
		&i.CustomerUsername,
		&i.SalesUsername,
		&i.ProductID,
		&i.PurchaseDate,
		&i.StartDate,
		&i.EndDate,
		&i.PricePaid,
		&i.DiscountAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerDurationsByUsername = `-- name: GetCustomerDurationsByUsername :many
SELECT
  id,
  customer_username,
  sales_username,
  product_id,
  purchase_date,
  start_date,
  end_date,
  price_paid,
  discount_amount,
  status,
  created_at,
  updated_at
FROM customer_durations
WHERE customer_username = ?
ORDER BY created_at DESC
`

func (q *Queries) GetCustomerDurationsByUsername(ctx context.Context, customerUsername sql.NullString) ([]CustomerDuration, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerDurationsByUsername, customerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerDuration
	for rows.Next() {
		var i CustomerDuration
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUsername,
			&i.SalesUsername,
			&i.ProductID,
			&i.PurchaseDate,
			&i.StartDate,
			&i.EndDate,
			&i.PricePaid,
			&i.DiscountAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
