// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package dbmodel

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO
  customers (
    username,
    health_info,
    address,
    company_name,
    company_position,
    marital_status,
    emergency_contact_name,
    emergency_contact_relationship,
    emergency_contact_phone,
    marketing_source
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCustomerParams struct {
	Username                     string                 `json:"username"`
	HealthInfo                   string                 `json:"healthInfo"`
	Address                      string                 `json:"address"`
	CompanyName                  string                 `json:"companyName"`
	CompanyPosition              string                 `json:"companyPosition"`
	MaritalStatus                CustomersMaritalStatus `json:"maritalStatus"`
	EmergencyContactName         string                 `json:"emergencyContactName"`
	EmergencyContactRelationship string                 `json:"emergencyContactRelationship"`
	EmergencyContactPhone        string                 `json:"emergencyContactPhone"`
	MarketingSource              string                 `json:"marketingSource"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, createCustomer,
		arg.Username,
		arg.HealthInfo,
		arg.Address,
		arg.CompanyName,
		arg.CompanyPosition,
		arg.MaritalStatus,
		arg.EmergencyContactName,
		arg.EmergencyContactRelationship,
		arg.EmergencyContactPhone,
		arg.MarketingSource,
	)
	return err
}
