// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_sessions.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const createCustomerSession = `-- name: CreateCustomerSession :exec
INSERT INTO customer_sessions (
  customer_username,
  trainer_username,
  product_id,
  sales_username,
  purchase_date,
  total_sessions,
  used_sessions,
  price_paid,
  discount_amount,
  status
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCustomerSessionParams struct {
	CustomerUsername sql.NullString         `json:"customerUsername"`
	TrainerUsername  sql.NullString         `json:"trainerUsername"`
	ProductID        sql.NullInt32          `json:"productId"`
	SalesUsername    sql.NullString         `json:"salesUsername"`
	PurchaseDate     time.Time              `json:"purchaseDate"`
	TotalSessions    int32                  `json:"totalSessions"`
	UsedSessions     sql.NullInt32          `json:"usedSessions"`
	PricePaid        string                 `json:"pricePaid"`
	DiscountAmount   sql.NullString         `json:"discountAmount"`
	Status           CustomerSessionsStatus `json:"status"`
}

func (q *Queries) CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerSession,
		arg.CustomerUsername,
		arg.TrainerUsername,
		arg.ProductID,
		arg.SalesUsername,
		arg.PurchaseDate,
		arg.TotalSessions,
		arg.UsedSessions,
		arg.PricePaid,
		arg.DiscountAmount,
		arg.Status,
	)
	return err
}
