// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_sessions.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const checkBookingPermission = `-- name: CheckBookingPermission :one
SELECT COUNT(*) as has_permission
FROM customer_sessions
WHERE customer_username = ?
  AND status = 'ACTIVE'
  AND used_sessions < total_sessions
`

// ตรวจสอบสิทธิ์การจองของ Customer
// ต้องมี Session package แบบ ACTIVE และยังมีสิทธิ์คงเหลือ (used_sessions < total_sessions)
func (q *Queries) CheckBookingPermission(ctx context.Context, customerUsername sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkBookingPermission, customerUsername)
	var has_permission int64
	err := row.Scan(&has_permission)
	return has_permission, err
}

const checkTrainerExists = `-- name: CheckTrainerExists :one
SELECT COUNT(username) AS cnt
FROM users
WHERE username = ? AND role = 'TRAINER'
`

func (q *Queries) CheckTrainerExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTrainerExists, username)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countCustomerSessions = `-- name: CountCustomerSessions :one
SELECT COUNT(cs.id) AS total_items
FROM customer_sessions cs
JOIN users cu ON cu.username = cs.customer_username
JOIN users tu ON tu.username = cs.trainer_username
JOIN products p ON p.id = cs.product_id
`

func (q *Queries) CountCustomerSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomerSessions)
	var total_items int64
	err := row.Scan(&total_items)
	return total_items, err
}

const createCustomerSession = `-- name: CreateCustomerSession :exec
INSERT INTO customer_sessions (
  customer_username,
  trainer_username,
  product_id,
  sales_username,
  purchase_date,
  total_sessions,
  used_sessions,
  price_paid,
  discount_amount,
  status
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCustomerSessionParams struct {
	CustomerUsername sql.NullString         `json:"customerUsername"`
	TrainerUsername  sql.NullString         `json:"trainerUsername"`
	ProductID        sql.NullInt32          `json:"productId"`
	SalesUsername    sql.NullString         `json:"salesUsername"`
	PurchaseDate     time.Time              `json:"purchaseDate"`
	TotalSessions    int32                  `json:"totalSessions"`
	UsedSessions     sql.NullInt32          `json:"usedSessions"`
	PricePaid        string                 `json:"pricePaid"`
	DiscountAmount   sql.NullString         `json:"discountAmount"`
	Status           CustomerSessionsStatus `json:"status"`
}

func (q *Queries) CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerSession,
		arg.CustomerUsername,
		arg.TrainerUsername,
		arg.ProductID,
		arg.SalesUsername,
		arg.PurchaseDate,
		arg.TotalSessions,
		arg.UsedSessions,
		arg.PricePaid,
		arg.DiscountAmount,
		arg.Status,
	)
	return err
}

const decrementUsedSessions = `-- name: DecrementUsedSessions :exec
UPDATE customer_sessions
SET used_sessions = used_sessions - 1
WHERE id = ?
  AND used_sessions > 0
`

// ยกเลิกการจอง - ลดจำนวนครั้งที่ใช้ไป (used_sessions - 1)
// Logic: UPDATE customer_sessions SET used_sessions = used_sessions - 1 WHERE id = ? AND used_sessions > 0
// Note: id คือ customer_sessions.id (ได้จาก training_schedules.session_id)
// ต้องมี used_sessions > 0 เพื่อป้องกันค่าติดลบ
func (q *Queries) DecrementUsedSessions(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, decrementUsedSessions, id)
	return err
}

const deleteCustomerSessionByID = `-- name: DeleteCustomerSessionByID :execresult
DELETE FROM customer_sessions
WHERE id = ?
`

func (q *Queries) DeleteCustomerSessionByID(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomerSessionByID, id)
}

const getActiveSessionByCustomer = `-- name: GetActiveSessionByCustomer :one
SELECT
  id,
  customer_username,
  trainer_username,
  total_sessions,
  used_sessions
FROM customer_sessions
WHERE customer_username = ?
  AND status = 'ACTIVE'
  AND used_sessions < total_sessions
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveSessionByCustomerRow struct {
	ID               int32          `json:"id"`
	CustomerUsername sql.NullString `json:"customerUsername"`
	TrainerUsername  sql.NullString `json:"trainerUsername"`
	TotalSessions    int32          `json:"totalSessions"`
	UsedSessions     sql.NullInt32  `json:"usedSessions"`
}

// หา Session package ACTIVE ของ Customer (สำหรับการจอง)
func (q *Queries) GetActiveSessionByCustomer(ctx context.Context, customerUsername sql.NullString) (GetActiveSessionByCustomerRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByCustomer, customerUsername)
	var i GetActiveSessionByCustomerRow
	err := row.Scan(
		&i.ID,
		&i.CustomerUsername,
		&i.TrainerUsername,
		&i.TotalSessions,
		&i.UsedSessions,
	)
	return i, err
}

const getCustomerActiveSessions = `-- name: GetCustomerActiveSessions :many
SELECT 
  cs.id,
  cs.customer_username,
  cs.trainer_username,
  cs.product_id,
  p.name AS product_name,
  cs.total_sessions,
  cs.used_sessions,
  (cs.total_sessions - cs.used_sessions) AS sessions_remaining,
  cs.purchase_date,
  cs.price_paid,
  cs.discount_amount,
  cs.status,
  cs.created_at
FROM customer_sessions cs
JOIN products p ON cs.product_id = p.id
WHERE cs.customer_username = ?
  AND cs.status = 'ACTIVE'
ORDER BY cs.created_at DESC
`

type GetCustomerActiveSessionsRow struct {
	ID                int32                  `json:"id"`
	CustomerUsername  sql.NullString         `json:"customerUsername"`
	TrainerUsername   sql.NullString         `json:"trainerUsername"`
	ProductID         sql.NullInt32          `json:"productId"`
	ProductName       string                 `json:"productName"`
	TotalSessions     int32                  `json:"totalSessions"`
	UsedSessions      sql.NullInt32          `json:"usedSessions"`
	SessionsRemaining int32                  `json:"sessionsRemaining"`
	PurchaseDate      time.Time              `json:"purchaseDate"`
	PricePaid         string                 `json:"pricePaid"`
	DiscountAmount    sql.NullString         `json:"discountAmount"`
	Status            CustomerSessionsStatus `json:"status"`
	CreatedAt         sql.NullTime           `json:"createdAt"`
}

// ดึงข้อมูล Session packages ที่ยัง ACTIVE ของลูกค้า
// JOIN กับ PRODUCTS เพื่อดึงชื่อแพ็กเกจและคำนวณ sessions คงเหลือ
func (q *Queries) GetCustomerActiveSessions(ctx context.Context, customerUsername sql.NullString) ([]GetCustomerActiveSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerActiveSessions, customerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerActiveSessionsRow
	for rows.Next() {
		var i GetCustomerActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUsername,
			&i.TrainerUsername,
			&i.ProductID,
			&i.ProductName,
			&i.TotalSessions,
			&i.UsedSessions,
			&i.SessionsRemaining,
			&i.PurchaseDate,
			&i.PricePaid,
			&i.DiscountAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerSessionByID = `-- name: GetCustomerSessionByID :one
SELECT
  cs.id,
  cs.customer_username,
  cs.trainer_username,
  cs.product_id,
  cs.sales_username,
  cs.purchase_date,
  cs.total_sessions,
  cs.used_sessions,
  cs.price_paid,
  cs.discount_amount,
  cs.status
FROM customer_sessions cs
WHERE cs.id = ?
`

type GetCustomerSessionByIDRow struct {
	ID               int32                  `json:"id"`
	CustomerUsername sql.NullString         `json:"customerUsername"`
	TrainerUsername  sql.NullString         `json:"trainerUsername"`
	ProductID        sql.NullInt32          `json:"productId"`
	SalesUsername    sql.NullString         `json:"salesUsername"`
	PurchaseDate     time.Time              `json:"purchaseDate"`
	TotalSessions    int32                  `json:"totalSessions"`
	UsedSessions     sql.NullInt32          `json:"usedSessions"`
	PricePaid        string                 `json:"pricePaid"`
	DiscountAmount   sql.NullString         `json:"discountAmount"`
	Status           CustomerSessionsStatus `json:"status"`
}

func (q *Queries) GetCustomerSessionByID(ctx context.Context, id int32) (GetCustomerSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerSessionByID, id)
	var i GetCustomerSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerUsername,
		&i.TrainerUsername,
		&i.ProductID,
		&i.SalesUsername,
		&i.PurchaseDate,
		&i.TotalSessions,
		&i.UsedSessions,
		&i.PricePaid,
		&i.DiscountAmount,
		&i.Status,
	)
	return i, err
}

const incrementUsedSessions = `-- name: IncrementUsedSessions :exec
UPDATE customer_sessions
SET used_sessions = used_sessions + 1
WHERE id = ?
`

// Q3C.6 - อัปเดตจำนวนครั้งที่ใช้ไปแล้ว
func (q *Queries) IncrementUsedSessions(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementUsedSessions, id)
	return err
}

const incrementUsedSessionsByUsername = `-- name: IncrementUsedSessionsByUsername :exec
UPDATE customer_sessions
SET used_sessions = used_sessions + 1,
    updated_at = NOW()
WHERE customer_username = ?
  AND status = 'ACTIVE'
  AND used_sessions < total_sessions
ORDER BY created_at DESC
LIMIT 1
`

// Q5C.2 - อัปเดตจำนวนครั้งที่ใช้ไปแล้วสำหรับ Check-in (Use Case 5C)
// ใช้ session package ACTIVE ที่ใหม่ที่สุด
func (q *Queries) IncrementUsedSessionsByUsername(ctx context.Context, customerUsername sql.NullString) error {
	_, err := q.db.ExecContext(ctx, incrementUsedSessionsByUsername, customerUsername)
	return err
}

const listCustomerSessions = `-- name: ListCustomerSessions :many
SELECT
  cs.id,
  cs.customer_username,
  cu.first_name  AS customer_first_name,
  cu.last_name   AS customer_last_name,
  cs.trainer_username,
  tu.first_name  AS trainer_first_name,
  tu.last_name   AS trainer_last_name,
  cs.product_id,
  p.name         AS product_name,
  p.type,
  p.category,
  p.session_amount,
  cs.sales_username,
  cs.purchase_date,
  cs.total_sessions,
  cs.used_sessions,
  (cs.total_sessions - cs.used_sessions) AS remaining_sessions,
  cs.price_paid,
  cs.discount_amount,
  cs.status
FROM customer_sessions cs
JOIN users cu ON cu.username = cs.customer_username
JOIN users tu ON tu.username = cs.trainer_username
JOIN products p ON p.id = cs.product_id
ORDER BY cs.created_at DESC, cs.id DESC
LIMIT ? OFFSET ?
`

type ListCustomerSessionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCustomerSessionsRow struct {
	ID                int32                  `json:"id"`
	CustomerUsername  sql.NullString         `json:"customerUsername"`
	CustomerFirstName string                 `json:"customerFirstName"`
	CustomerLastName  string                 `json:"customerLastName"`
	TrainerUsername   sql.NullString         `json:"trainerUsername"`
	TrainerFirstName  string                 `json:"trainerFirstName"`
	TrainerLastName   string                 `json:"trainerLastName"`
	ProductID         sql.NullInt32          `json:"productId"`
	ProductName       string                 `json:"productName"`
	Type              ProductsType           `json:"type"`
	Category          ProductsCategory       `json:"category"`
	SessionAmount     sql.NullInt32          `json:"sessionAmount"`
	SalesUsername     sql.NullString         `json:"salesUsername"`
	PurchaseDate      time.Time              `json:"purchaseDate"`
	TotalSessions     int32                  `json:"totalSessions"`
	UsedSessions      sql.NullInt32          `json:"usedSessions"`
	RemainingSessions int32                  `json:"remainingSessions"`
	PricePaid         string                 `json:"pricePaid"`
	DiscountAmount    sql.NullString         `json:"discountAmount"`
	Status            CustomerSessionsStatus `json:"status"`
}

func (q *Queries) ListCustomerSessions(ctx context.Context, arg ListCustomerSessionsParams) ([]ListCustomerSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSessionsRow
	for rows.Next() {
		var i ListCustomerSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUsername,
			&i.CustomerFirstName,
			&i.CustomerLastName,
			&i.TrainerUsername,
			&i.TrainerFirstName,
			&i.TrainerLastName,
			&i.ProductID,
			&i.ProductName,
			&i.Type,
			&i.Category,
			&i.SessionAmount,
			&i.SalesUsername,
			&i.PurchaseDate,
			&i.TotalSessions,
			&i.UsedSessions,
			&i.RemainingSessions,
			&i.PricePaid,
			&i.DiscountAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerSessionEditableFields = `-- name: UpdateCustomerSessionEditableFields :exec
UPDATE customer_sessions
SET trainer_username = ?,
    price_paid       = ?,
    discount_amount  = ?,
    status           = ?,
    updated_at       = NOW()
WHERE id = ?
`

type UpdateCustomerSessionEditableFieldsParams struct {
	TrainerUsername sql.NullString         `json:"trainerUsername"`
	PricePaid       string                 `json:"pricePaid"`
	DiscountAmount  sql.NullString         `json:"discountAmount"`
	Status          CustomerSessionsStatus `json:"status"`
	ID              int32                  `json:"id"`
}

func (q *Queries) UpdateCustomerSessionEditableFields(ctx context.Context, arg UpdateCustomerSessionEditableFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerSessionEditableFields,
		arg.TrainerUsername,
		arg.PricePaid,
		arg.DiscountAmount,
		arg.Status,
		arg.ID,
	)
	return err
}
