// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbmodel

import (
	"context"
	"time"
)

const activeMembersToday = `-- name: ActiveMembersToday :one
SELECT CAST(COUNT(DISTINCT customer_username) AS SIGNED) AS c
FROM customer_durations
WHERE status = 'ACTIVE'
  AND CURDATE() BETWEEN DATE(start_date) AND DATE(end_date)
`

func (q *Queries) ActiveMembersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeMembersToday)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const checkinsToday = `-- name: CheckinsToday :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM customer_logs
WHERE log_type = 'CHECK_IN'
  AND DATE(` + "`" + `created_at` + "`" + `) = CURDATE()
`

func (q *Queries) CheckinsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkinsToday)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const completedPTInRange = `-- name: CompletedPTInRange :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM training_schedules
WHERE schedule_type = 'APPOINTMENT'
  AND start_time BETWEEN ? AND ?
  AND start_time < NOW()
`

type CompletedPTInRangeParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) CompletedPTInRange(ctx context.Context, arg CompletedPTInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, completedPTInRange, arg.Start, arg.End)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const newMembersInRange = `-- name: NewMembersInRange :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM users
WHERE role = 'CUSTOMER'
  AND created_at BETWEEN ? AND ?
`

type NewMembersInRangeParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) NewMembersInRange(ctx context.Context, arg NewMembersInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, newMembersInRange, arg.Start, arg.End)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const revenueDurations = `-- name: RevenueDurations :one
SELECT CAST(COALESCE(SUM(price_paid), 0) AS SIGNED) AS total
FROM customer_durations
WHERE purchase_date BETWEEN ? AND ?
`

type RevenueDurationsParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) RevenueDurations(ctx context.Context, arg RevenueDurationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, revenueDurations, arg.Start, arg.End)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const revenueSessions = `-- name: RevenueSessions :one
SELECT CAST(COALESCE(SUM(price_paid), 0) AS SIGNED) AS total
FROM customer_sessions
WHERE purchase_date BETWEEN ? AND ?
`

type RevenueSessionsParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) RevenueSessions(ctx context.Context, arg RevenueSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, revenueSessions, arg.Start, arg.End)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const topSellingProductsDurations = `-- name: TopSellingProductsDurations :many
SELECT p.name AS name, COUNT(*) AS units
FROM customer_durations d
JOIN products p ON p.id = d.product_id
WHERE d.purchase_date BETWEEN ? AND ?
GROUP BY p.name
ORDER BY units DESC
`

type TopSellingProductsDurationsParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type TopSellingProductsDurationsRow struct {
	Name  string `json:"name"`
	Units int64  `json:"units"`
}

func (q *Queries) TopSellingProductsDurations(ctx context.Context, arg TopSellingProductsDurationsParams) ([]TopSellingProductsDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, topSellingProductsDurations, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopSellingProductsDurationsRow
	for rows.Next() {
		var i TopSellingProductsDurationsRow
		if err := rows.Scan(&i.Name, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topSellingProductsSessions = `-- name: TopSellingProductsSessions :many
SELECT p.name AS name, COUNT(*) AS units
FROM customer_sessions s
JOIN products p ON p.id = s.product_id
WHERE s.purchase_date BETWEEN ? AND ?
GROUP BY p.name
ORDER BY units DESC
`

type TopSellingProductsSessionsParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type TopSellingProductsSessionsRow struct {
	Name  string `json:"name"`
	Units int64  `json:"units"`
}

func (q *Queries) TopSellingProductsSessions(ctx context.Context, arg TopSellingProductsSessionsParams) ([]TopSellingProductsSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, topSellingProductsSessions, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopSellingProductsSessionsRow
	for rows.Next() {
		var i TopSellingProductsSessionsRow
		if err := rows.Scan(&i.Name, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
