// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbmodel

import (
	"context"
	"time"
)

const activeMembersToday = `-- name: ActiveMembersToday :one
SELECT CAST(COUNT(DISTINCT Customer_Username) AS SIGNED) AS c
FROM CUSTOMER_DURATIONS
WHERE Status = 'ACTIVE'
  AND CURDATE() BETWEEN DATE(Start_Date) AND DATE(End_Date)
`

func (q *Queries) ActiveMembersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeMembersToday)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const checkinsToday = `-- name: CheckinsToday :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM CUSTOMER_LOGS
WHERE Log_Type = 'CHECK_IN'
  AND DATE(` + "`" + `Timestamp` + "`" + `) = CURDATE()
`

func (q *Queries) CheckinsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkinsToday)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const completedPTInRange = `-- name: CompletedPTInRange :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM TRAINING_SCHEDULES
WHERE Schedule_Type = 'APPOINTMENT'
  AND Start_Time BETWEEN ? AND ?
  AND Start_Time < NOW()
`

type CompletedPTInRangeParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) CompletedPTInRange(ctx context.Context, arg CompletedPTInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, completedPTInRange, arg.Start, arg.End)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const newMembersInRange = `-- name: NewMembersInRange :one
SELECT CAST(COUNT(*) AS SIGNED) AS c
FROM USERS
WHERE Role = 'CUSTOMER'
  AND Created_At BETWEEN ? AND ?
`

type NewMembersInRangeParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) NewMembersInRange(ctx context.Context, arg NewMembersInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, newMembersInRange, arg.Start, arg.End)
	var c int64
	err := row.Scan(&c)
	return c, err
}

const topSellingProducts = `-- name: TopSellingProducts :many
SELECT p.Name AS name, COUNT(*) AS units
FROM (
  SELECT Product_Id FROM CUSTOMER_DURATIONS
  WHERE Purchase_Date BETWEEN ? AND ?
  UNION ALL
  SELECT Product_Id FROM CUSTOMER_SESSIONS
  WHERE Purchase_Date BETWEEN ? AND ?
) s
JOIN PRODUCTS p ON p.Product_Id = s.Product_Id
GROUP BY p.Name
ORDER BY units DESC
LIMIT 5
`

type TopSellingProductsParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type TopSellingProductsRow struct {
	Name  string `json:"name"`
	Units int64  `json:"units"`
}

func (q *Queries) TopSellingProducts(ctx context.Context, arg TopSellingProductsParams) ([]TopSellingProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, topSellingProducts,
		arg.Start,
		arg.Start,
		arg.End,
		arg.End,
		arg.Start,
		arg.Start,
		arg.End,
		arg.End,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopSellingProductsRow
	for rows.Next() {
		var i TopSellingProductsRow
		if err := rows.Scan(&i.Name, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalRevenue = `-- name: TotalRevenue :one
SELECT CAST(COALESCE(SUM(amt), 0) AS SIGNED) AS total
FROM (
  SELECT Price_Paid AS amt
  FROM CUSTOMER_DURATIONS
  WHERE Purchase_Date BETWEEN ? AND ?
  UNION ALL
  SELECT Price_Paid AS amt
  FROM CUSTOMER_SESSIONS
  WHERE Purchase_Date BETWEEN ? AND ?
) t
`

type TotalRevenueParams struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

func (q *Queries) TotalRevenue(ctx context.Context, arg TotalRevenueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalRevenue,
		arg.Start,
		arg.Start,
		arg.End,
		arg.End,
		arg.Start,
		arg.Start,
		arg.End,
		arg.End,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}
