// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}
