// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_accounts.sql

package dbmodel

import (
	"context"
)

const createPaymentAccount = `-- name: CreatePaymentAccount :exec
INSERT INTO payment_accounts (
  account_name,
  account_number,
  bank_name,
  qr_code_image_url,
  is_active
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreatePaymentAccountParams struct {
	AccountName    string `json:"accountName"`
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	QrCodeImageUrl string `json:"qrCodeImageUrl"`
	IsActive       bool   `json:"isActive"`
}

func (q *Queries) CreatePaymentAccount(ctx context.Context, arg CreatePaymentAccountParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentAccount,
		arg.AccountName,
		arg.AccountNumber,
		arg.BankName,
		arg.QrCodeImageUrl,
		arg.IsActive,
	)
	return err
}
