// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_verifications.sql

package dbmodel

import (
	"context"
	"database/sql"
)

const checkDuplicatePayment = `-- name: CheckDuplicatePayment :one
SELECT COUNT(id) AS duplicate_count
FROM payment_verifications
WHERE customer_username = ?
  AND product_id = ?
  AND ABS(amount - ?) < 0.01
  AND verification_status = 'VERIFIED'
  AND created_at >= DATE_SUB(NOW(), INTERVAL 24 HOUR)
`

type CheckDuplicatePaymentParams struct {
	CustomerUsername string `json:"customerUsername"`
	ProductID        int32  `json:"productId"`
	Amount           string `json:"amount"`
}

// Q_VERIFY_2: Check duplicate payment slip (by customer + product + amount within 24 hours)
func (q *Queries) CheckDuplicatePayment(ctx context.Context, arg CheckDuplicatePaymentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicatePayment, arg.CustomerUsername, arg.ProductID, arg.Amount)
	var duplicate_count int64
	err := row.Scan(&duplicate_count)
	return duplicate_count, err
}

const countPaymentVerificationsByStatus = `-- name: CountPaymentVerificationsByStatus :one
SELECT COUNT(id) AS total
FROM payment_verifications
WHERE verification_status = ?
`

// Q_VERIFY_6: Count payment verifications by status
func (q *Queries) CountPaymentVerificationsByStatus(ctx context.Context, verificationStatus PaymentVerificationsVerificationStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentVerificationsByStatus, verificationStatus)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getPaymentVerificationById = `-- name: GetPaymentVerificationById :one
SELECT
  id,
  customer_username,
  product_id,
  amount,
  slip_file_path,
  slip_id,
  verification_status,
  slip2go_response,
  verified_at,
  created_at,
  updated_at
FROM payment_verifications
WHERE id = ?
`

// Q_VERIFY_4: Get payment verification by ID
func (q *Queries) GetPaymentVerificationById(ctx context.Context, id int32) (PaymentVerification, error) {
	row := q.db.QueryRowContext(ctx, getPaymentVerificationById, id)
	var i PaymentVerification
	err := row.Scan(
		&i.ID,
		&i.CustomerUsername,
		&i.ProductID,
		&i.Amount,
		&i.SlipFilePath,
		&i.SlipID,
		&i.VerificationStatus,
		&i.Slip2goResponse,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentVerification = `-- name: InsertPaymentVerification :execresult

INSERT INTO payment_verifications (
  customer_username,
  product_id,
  amount,
  slip_file_path,
  verification_status
) VALUES (?, ?, ?, ?, ?)
`

type InsertPaymentVerificationParams struct {
	CustomerUsername   string                                 `json:"customerUsername"`
	ProductID          int32                                  `json:"productId"`
	Amount             string                                 `json:"amount"`
	SlipFilePath       sql.NullString                         `json:"slipFilePath"`
	VerificationStatus PaymentVerificationsVerificationStatus `json:"verificationStatus"`
}

// Payment Slip Verification Queries
// Q_VERIFY_1: Insert payment verification log
func (q *Queries) InsertPaymentVerification(ctx context.Context, arg InsertPaymentVerificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPaymentVerification,
		arg.CustomerUsername,
		arg.ProductID,
		arg.Amount,
		arg.SlipFilePath,
		arg.VerificationStatus,
	)
}

const listPaymentVerificationsByCustomer = `-- name: ListPaymentVerificationsByCustomer :many
SELECT
  id,
  customer_username,
  product_id,
  amount,
  slip_file_path,
  slip_id,
  verification_status,
  verified_at,
  created_at
FROM payment_verifications
WHERE customer_username = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPaymentVerificationsByCustomerParams struct {
	CustomerUsername string `json:"customerUsername"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

type ListPaymentVerificationsByCustomerRow struct {
	ID                 int32                                  `json:"id"`
	CustomerUsername   string                                 `json:"customerUsername"`
	ProductID          int32                                  `json:"productId"`
	Amount             string                                 `json:"amount"`
	SlipFilePath       sql.NullString                         `json:"slipFilePath"`
	SlipID             sql.NullString                         `json:"slipId"`
	VerificationStatus PaymentVerificationsVerificationStatus `json:"verificationStatus"`
	VerifiedAt         sql.NullTime                           `json:"verifiedAt"`
	CreatedAt          sql.NullTime                           `json:"createdAt"`
}

// Q_VERIFY_5: List all payment verifications for a customer
func (q *Queries) ListPaymentVerificationsByCustomer(ctx context.Context, arg ListPaymentVerificationsByCustomerParams) ([]ListPaymentVerificationsByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentVerificationsByCustomer, arg.CustomerUsername, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentVerificationsByCustomerRow
	for rows.Next() {
		var i ListPaymentVerificationsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUsername,
			&i.ProductID,
			&i.Amount,
			&i.SlipFilePath,
			&i.SlipID,
			&i.VerificationStatus,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentVerificationStatus = `-- name: UpdatePaymentVerificationStatus :exec
UPDATE payment_verifications
SET 
  verification_status = ?,
  slip_id = ?,
  slip2go_response = ?,
  verified_at = NOW(),
  updated_at = NOW()
WHERE id = ?
`

type UpdatePaymentVerificationStatusParams struct {
	VerificationStatus PaymentVerificationsVerificationStatus `json:"verificationStatus"`
	SlipID             sql.NullString                         `json:"slipId"`
	Slip2goResponse    sql.NullString                         `json:"slip2goResponse"`
	ID                 int32                                  `json:"id"`
}

// Q_VERIFY_3: Update payment verification status after Slip2Go verification
func (q *Queries) UpdatePaymentVerificationStatus(ctx context.Context, arg UpdatePaymentVerificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentVerificationStatus,
		arg.VerificationStatus,
		arg.SlipID,
		arg.Slip2goResponse,
		arg.ID,
	)
	return err
}
