// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_accounts.sql

package dbmodel

import (
	"context"
	"database/sql"
)

const countPaymentAccounts = `-- name: CountPaymentAccounts :one
SELECT COUNT(pa.id) AS total_items
FROM payment_accounts pa
`

func (q *Queries) CountPaymentAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentAccounts)
	var total_items int64
	err := row.Scan(&total_items)
	return total_items, err
}

const createPaymentAccount = `-- name: CreatePaymentAccount :exec
INSERT INTO payment_accounts (
  account_name,
  account_number,
  bank_name,
  qr_code_image_url,
  is_active
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreatePaymentAccountParams struct {
	AccountName    string `json:"accountName"`
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	QrCodeImageUrl string `json:"qrCodeImageUrl"`
	IsActive       bool   `json:"isActive"`
}

func (q *Queries) CreatePaymentAccount(ctx context.Context, arg CreatePaymentAccountParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentAccount,
		arg.AccountName,
		arg.AccountNumber,
		arg.BankName,
		arg.QrCodeImageUrl,
		arg.IsActive,
	)
	return err
}

const deletePaymentAccountByID = `-- name: DeletePaymentAccountByID :execresult
DELETE FROM payment_accounts
WHERE id = ?
`

func (q *Queries) DeletePaymentAccountByID(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePaymentAccountByID, id)
}

const getPaymentInfoByProductId = `-- name: GetPaymentInfoByProductId :one
SELECT 
  p.id AS product_id,
  p.name AS product_name,
  p.type AS product_type,
  p.category AS product_category,
  p.list_price,
  p.duration_days,
  p.session_amount,
  pa.id AS payment_account_id,
  pa.account_name,
  pa.account_number,
  pa.bank_name,
  pa.qr_code_image_url,
  pa.is_active AS account_active
FROM products p
JOIN payment_accounts pa ON pa.id = p.payment_account_id
WHERE p.id = ?
  AND p.is_active = TRUE
  AND pa.is_active = TRUE
`

type GetPaymentInfoByProductIdRow struct {
	ProductID        int32            `json:"productId"`
	ProductName      string           `json:"productName"`
	ProductType      ProductsType     `json:"productType"`
	ProductCategory  ProductsCategory `json:"productCategory"`
	ListPrice        string           `json:"listPrice"`
	DurationDays     sql.NullInt32    `json:"durationDays"`
	SessionAmount    sql.NullInt32    `json:"sessionAmount"`
	PaymentAccountID int32            `json:"paymentAccountId"`
	AccountName      string           `json:"accountName"`
	AccountNumber    string           `json:"accountNumber"`
	BankName         string           `json:"bankName"`
	QrCodeImageUrl   string           `json:"qrCodeImageUrl"`
	AccountActive    bool             `json:"accountActive"`
}

// Q5S.1: ดึงข้อมูลสินค้าและบัญชีรับชำระเงินเพื่อแสดงหน้าชำระเงิน
func (q *Queries) GetPaymentInfoByProductId(ctx context.Context, id int32) (GetPaymentInfoByProductIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentInfoByProductId, id)
	var i GetPaymentInfoByProductIdRow
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.ProductType,
		&i.ProductCategory,
		&i.ListPrice,
		&i.DurationDays,
		&i.SessionAmount,
		&i.PaymentAccountID,
		&i.AccountName,
		&i.AccountNumber,
		&i.BankName,
		&i.QrCodeImageUrl,
		&i.AccountActive,
	)
	return i, err
}

const insertPaymentAccount = `-- name: InsertPaymentAccount :execresult
INSERT INTO payment_accounts (
  account_name,
  account_number,
  bank_name,
  qr_code_image_url,
  is_active
) VALUES (?, ?, ?, ?, ?)
`

type InsertPaymentAccountParams struct {
	AccountName    string `json:"accountName"`
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	QrCodeImageUrl string `json:"qrCodeImageUrl"`
	IsActive       bool   `json:"isActive"`
}

func (q *Queries) InsertPaymentAccount(ctx context.Context, arg InsertPaymentAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPaymentAccount,
		arg.AccountName,
		arg.AccountNumber,
		arg.BankName,
		arg.QrCodeImageUrl,
		arg.IsActive,
	)
}

const listPaymentAccounts = `-- name: ListPaymentAccounts :many
SELECT
  pa.id,
  pa.account_name,
  pa.account_number,
  pa.bank_name,
  pa.qr_code_image_url,
  (pa.is_active = 1)
FROM payment_accounts pa
ORDER BY pa.is_active DESC, pa.id DESC
LIMIT ? OFFSET ?
`

type ListPaymentAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPaymentAccountsRow struct {
	ID             int32  `json:"id"`
	AccountName    string `json:"accountName"`
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	QrCodeImageUrl string `json:"qrCodeImageUrl"`
	Column6        bool   `json:"column6"`
}

func (q *Queries) ListPaymentAccounts(ctx context.Context, arg ListPaymentAccountsParams) ([]ListPaymentAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentAccountsRow
	for rows.Next() {
		var i ListPaymentAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.AccountNumber,
			&i.BankName,
			&i.QrCodeImageUrl,
			&i.Column6,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAccountByID = `-- name: UpdatePaymentAccountByID :exec
UPDATE payment_accounts
SET
  account_name      = ?,
  account_number    = ?,
  bank_name         = ?,
  qr_code_image_url = ?,
  is_active         = ?
WHERE id = ?
`

type UpdatePaymentAccountByIDParams struct {
	AccountName    string `json:"accountName"`
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	QrCodeImageUrl string `json:"qrCodeImageUrl"`
	IsActive       bool   `json:"isActive"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdatePaymentAccountByID(ctx context.Context, arg UpdatePaymentAccountByIDParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentAccountByID,
		arg.AccountName,
		arg.AccountNumber,
		arg.BankName,
		arg.QrCodeImageUrl,
		arg.IsActive,
		arg.ID,
	)
	return err
}
