// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbmodel

import (
	"context"
	"database/sql"
)

const listDurations = `-- name: ListDurations :many
SELECT
  id,             
  name,             
  type,            
  category,         
  list_price,       
  duration_days,    
  session_amount,   
  is_active
FROM products
WHERE
  type = 'DURATION'
  AND is_active = TRUE
ORDER BY list_price ASC
`

type ListDurationsRow struct {
	ID            uint64           `json:"id"`
	Name          string           `json:"name"`
	Type          ProductsType     `json:"type"`
	Category      ProductsCategory `json:"category"`
	ListPrice     string           `json:"listPrice"`
	DurationDays  sql.NullInt32    `json:"durationDays"`
	SessionAmount sql.NullInt32    `json:"sessionAmount"`
	IsActive      sql.NullBool     `json:"isActive"`
}

func (q *Queries) ListDurations(ctx context.Context) ([]ListDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDurationsRow
	for rows.Next() {
		var i ListDurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.ListPrice,
			&i.DurationDays,
			&i.SessionAmount,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT
  id,
  name,
  type,
  category,
  list_price,
  duration_days,
  session_amount,
  is_active
FROM products
WHERE
  type = 'SESSION'
  AND is_active = TRUE
ORDER BY list_price ASC
`

type ListSessionsRow struct {
	ID            uint64           `json:"id"`
	Name          string           `json:"name"`
	Type          ProductsType     `json:"type"`
	Category      ProductsCategory `json:"category"`
	ListPrice     string           `json:"listPrice"`
	DurationDays  sql.NullInt32    `json:"durationDays"`
	SessionAmount sql.NullInt32    `json:"sessionAmount"`
	IsActive      sql.NullBool     `json:"isActive"`
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.ListPrice,
			&i.DurationDays,
			&i.SessionAmount,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
