// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbmodel

import (
	"context"
	"database/sql"
)

const getProductById = `-- name: GetProductById :one
SELECT
  id,
  name,
  type,
  category,
  list_price,
  duration_days,
  session_amount,
  is_active,
  payment_account_id,
  created_at,
  updated_at
FROM products
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.ListPrice,
		&i.DurationDays,
		&i.SessionAmount,
		&i.IsActive,
		&i.PaymentAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT
  id,
  name,
  type,
  category,
  list_price,
  duration_days,
  session_amount,
  is_active,
  payment_account_id,
  created_at,
  updated_at
FROM products
WHERE is_active = TRUE
ORDER BY category, list_price ASC
`

func (q *Queries) ListAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.ListPrice,
			&i.DurationDays,
			&i.SessionAmount,
			&i.IsActive,
			&i.PaymentAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDurations = `-- name: ListDurations :many
SELECT
  id,             
  name,             
  type,            
  category,         
  list_price,       
  duration_days,    
  session_amount,   
  is_active,
  payment_account_id
FROM products
WHERE
  type = 'DURATION'
  AND is_active = TRUE
ORDER BY list_price ASC
`

type ListDurationsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Type             ProductsType     `json:"type"`
	Category         ProductsCategory `json:"category"`
	ListPrice        string           `json:"listPrice"`
	DurationDays     sql.NullInt32    `json:"durationDays"`
	SessionAmount    sql.NullInt32    `json:"sessionAmount"`
	IsActive         sql.NullBool     `json:"isActive"`
	PaymentAccountID int32            `json:"paymentAccountId"`
}

func (q *Queries) ListDurations(ctx context.Context) ([]ListDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDurationsRow
	for rows.Next() {
		var i ListDurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.ListPrice,
			&i.DurationDays,
			&i.SessionAmount,
			&i.IsActive,
			&i.PaymentAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT
  id,
  name,
  type,
  category,
  list_price,
  duration_days,
  session_amount,
  is_active,
  payment_account_id
FROM products
WHERE
  type = 'SESSION'
  AND is_active = TRUE
ORDER BY list_price ASC
`

type ListSessionsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Type             ProductsType     `json:"type"`
	Category         ProductsCategory `json:"category"`
	ListPrice        string           `json:"listPrice"`
	DurationDays     sql.NullInt32    `json:"durationDays"`
	SessionAmount    sql.NullInt32    `json:"sessionAmount"`
	IsActive         sql.NullBool     `json:"isActive"`
	PaymentAccountID int32            `json:"paymentAccountId"`
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.ListPrice,
			&i.DurationDays,
			&i.SessionAmount,
			&i.IsActive,
			&i.PaymentAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
