// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodel

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActiveMembersToday(ctx context.Context) (int64, error)
	// Q3C.6 - บันทึกการจองนัด (APPOINTMENT)
	BookAppointment(ctx context.Context, arg BookAppointmentParams) error
	// ตรวจสอบสิทธิ์การจองของ Customer
	// ต้องมี Session package แบบ ACTIVE และยังมีสิทธิ์คงเหลือ (used_sessions < total_sessions)
	CheckBookingPermission(ctx context.Context, customerUsername sql.NullString) (int64, error)
	CheckCustomerGmailExistsExcept(ctx context.Context, arg CheckCustomerGmailExistsExceptParams) (int64, error)
	CheckCustomerPhoneExistsExcept(ctx context.Context, arg CheckCustomerPhoneExistsExceptParams) (int64, error)
	// Q3P.3: Check if day-off overlaps with existing appointments
	CheckDayOffAppointmentOverlap(ctx context.Context, arg CheckDayOffAppointmentOverlapParams) (int64, error)
	// Q3P.2: Check if day-off already exists for the same date
	CheckDayOffDuplicate(ctx context.Context, arg CheckDayOffDuplicateParams) (int64, error)
	CheckGmailExists(ctx context.Context, lower string) (int64, error)
	CheckGmailExistsExceptUsername(ctx context.Context, arg CheckGmailExistsExceptUsernameParams) (int64, error)
	CheckGmailExistsUser(ctx context.Context, gmail string) (int64, error)
	CheckPaymentAccountActive(ctx context.Context, id int32) (int64, error)
	CheckPhoneExists(ctx context.Context, phoneNumber string) (int64, error)
	CheckPhoneExistsExceptUsername(ctx context.Context, arg CheckPhoneExistsExceptUsernameParams) (int64, error)
	CheckPhoneNumberExistsUser(ctx context.Context, phoneNumber string) (int64, error)
	// ตรวจสอบว่ามีนัดซ้อนทับหรือไม่
	CheckScheduleOverlap(ctx context.Context, arg CheckScheduleOverlapParams) (int64, error)
	// Q1P.2: Check Time Overlap (Validation before adding)
	CheckTimeOverlap(ctx context.Context, arg CheckTimeOverlapParams) (int64, error)
	// Q3C.5 - ตรวจสอบว่าช่วงเวลาที่เลือกยังว่างอยู่จริง
	// คืนค่า overlapped_count ถ้าเป็น 0 แสดงว่ายังว่างอยู่
	// Logic: ช่วงเวลาซ้อนทับกันเมื่อ start_time < endTime AND end_time > startTime
	CheckTimeSlotAvailability(ctx context.Context, arg CheckTimeSlotAvailabilityParams) (int64, error)
	CheckTrainerExists(ctx context.Context, username string) (int64, error)
	CheckUsernameExists(ctx context.Context, username string) (int64, error)
	CheckinsToday(ctx context.Context) (int64, error)
	CompletedPTInRange(ctx context.Context, arg CompletedPTInRangeParams) (int64, error)
	// นับจำนวนนัดหมายของเทรนเนอร์ในวันที่กำหนด
	CountAppointmentsOnDate(ctx context.Context, arg CountAppointmentsOnDateParams) (int64, error)
	CountCustomerDurations(ctx context.Context) (int64, error)
	CountCustomerLogs(ctx context.Context) (int64, error)
	CountCustomerSessions(ctx context.Context) (int64, error)
	CountCustomers(ctx context.Context) (int64, error)
	CountPaymentAccounts(ctx context.Context) (int64, error)
	CountProductReferences(ctx context.Context, arg CountProductReferencesParams) (CountProductReferencesRow, error)
	CountProducts(ctx context.Context) (int64, error)
	CountStaffs(ctx context.Context) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateCustomerDuration(ctx context.Context, arg CreateCustomerDurationParams) error
	CreateCustomerLog(ctx context.Context, arg CreateCustomerLogParams) error
	CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) error
	// Q3P.4: Create day-off
	CreateDayOff(ctx context.Context, arg CreateDayOffParams) error
	CreatePaymentAccount(ctx context.Context, arg CreatePaymentAccountParams) error
	CreateStaff(ctx context.Context, arg CreateStaffParams) error
	// Q1P.3: Create Trainer Availability (Add Working Time)
	CreateTrainerAvailability(ctx context.Context, arg CreateTrainerAvailabilityParams) error
	CreateTrainingSchedule(ctx context.Context, arg CreateTrainingScheduleParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// ยกเลิกการจอง - ลดจำนวนครั้งที่ใช้ไป (used_sessions - 1)
	// Logic: UPDATE customer_sessions SET used_sessions = used_sessions - 1 WHERE id = ? AND used_sessions > 0
	// Note: id คือ customer_sessions.id (ได้จาก training_schedules.session_id)
	// ต้องมี used_sessions > 0 เพื่อป้องกันค่าติดลบ
	DecrementUsedSessions(ctx context.Context, id int32) error
	// ยกเลิกการจอง - ลบ training_schedule record
	// Logic: DELETE FROM training_schedules WHERE id = ? AND schedule_type = 'APPOINTMENT'
	// Note: ใช้ id เพียงอย่างเดียว เพราะ id เป็น Primary Key (unique)
	// การตรวจสอบ customer_username ทำใน use case layer ก่อนเรียก query นี้
	DeleteAppointment(ctx context.Context, id int32) error
	DeleteCustomerByUsername(ctx context.Context, username string) error
	DeleteCustomerDurationByCustomer(ctx context.Context, customerUsername sql.NullString) error
	DeleteCustomerDurationByID(ctx context.Context, id int32) (sql.Result, error)
	DeleteCustomerDurationBySales(ctx context.Context, salesUsername sql.NullString) error
	DeleteCustomerLogByID(ctx context.Context, id int32) (sql.Result, error)
	DeleteCustomerLogsByCustomer(ctx context.Context, customerUsername sql.NullString) error
	DeleteCustomerSessionByCustomer(ctx context.Context, customerUsername sql.NullString) error
	DeleteCustomerSessionByID(ctx context.Context, id int32) (sql.Result, error)
	DeleteCustomerSessionBySales(ctx context.Context, salesUsername sql.NullString) error
	DeleteCustomerSessionByTrainer(ctx context.Context, trainerUsername sql.NullString) error
	// Q3P.5: Delete day-off
	DeleteDayOff(ctx context.Context, id int32) error
	DeletePaymentAccountByID(ctx context.Context, id int32) (sql.Result, error)
	DeleteProductByID(ctx context.Context, id int32) (sql.Result, error)
	// Q1P.5: Delete Trainer Availability (Remove Working Time)
	DeleteTrainerAvailability(ctx context.Context, id int32) error
	DeleteTrainerAvailabilityByTrainer(ctx context.Context, trainerUsername string) error
	DeleteTrainingScheduleByCustomer(ctx context.Context, customerUsername sql.NullString) error
	DeleteTrainingScheduleByTrainer(ctx context.Context, trainerUsername sql.NullString) error
	DeleteUserByUsername(ctx context.Context, username string) error
	// Q4S.1 แก้ไข: หาเทรนเนอร์ที่ว่างในวันและเวลาที่กำหนด
	FindAvailableTrainers(ctx context.Context, arg FindAvailableTrainersParams) ([]FindAvailableTrainersRow, error)
	// หา Session package ACTIVE ของ Customer (สำหรับการจอง)
	GetActiveSessionByCustomer(ctx context.Context, customerUsername sql.NullString) (GetActiveSessionByCustomerRow, error)
	// ดึงข้อมูลการจองตาม ID เพื่อตรวจสอบก่อนยกเลิก
	GetAppointmentById(ctx context.Context, id int32) (GetAppointmentByIdRow, error)
	// Q3C.3b - ดึงนัดที่ถูกจองแล้ว (APPOINTMENT)
	GetAppointmentSchedules(ctx context.Context, arg GetAppointmentSchedulesParams) ([]GetAppointmentSchedulesRow, error)
	// ดึงข้อมูล Duration packages ที่ยัง ACTIVE ของลูกค้า
	// JOIN กับ PRODUCTS เพื่อดึงชื่อแพ็กเกจและคำนวณ วันคงเหลือที่ยังใช้งานได้
	GetCustomerActiveDuration(ctx context.Context, customerUsername sql.NullString) ([]GetCustomerActiveDurationRow, error)
	// ดึงข้อมูล Session packages ที่ยัง ACTIVE ของลูกค้า
	// JOIN กับ PRODUCTS เพื่อดึงชื่อแพ็กเกจและคำนวณ sessions คงเหลือ
	GetCustomerActiveSessions(ctx context.Context, customerUsername sql.NullString) ([]GetCustomerActiveSessionsRow, error)
	GetCustomerByUsername(ctx context.Context, username string) (GetCustomerByUsernameRow, error)
	GetCustomerDurationByID(ctx context.Context, id int32) (GetCustomerDurationByIDRow, error)
	GetCustomerDurationById(ctx context.Context, id int32) (CustomerDuration, error)
	GetCustomerDurationsByUsername(ctx context.Context, customerUsername sql.NullString) ([]CustomerDuration, error)
	GetCustomerLogByID(ctx context.Context, id int32) (GetCustomerLogByIDRow, error)
	GetCustomerSessionByID(ctx context.Context, id int32) (GetCustomerSessionByIDRow, error)
	// Q3C.3a - ดึงวันหยุดหรือช่วงเวลาที่ไม่รับนัด (DAY_OFF)
	GetDayOffSchedules(ctx context.Context, arg GetDayOffSchedulesParams) ([]GetDayOffSchedulesRow, error)
	GetDurationDaysForDurationID(ctx context.Context, id int32) (sql.NullInt32, error)
	GetPaymentAccountByID(ctx context.Context, id int32) (GetPaymentAccountByIDRow, error)
	// Q5S.1: ดึงข้อมูลสินค้าและบัญชีรับชำระเงินเพื่อแสดงหน้าชำระเงิน
	GetPaymentInfoByProductId(ctx context.Context, id int32) (GetPaymentInfoByProductIdRow, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	GetStaffByUsername(ctx context.Context, username string) (GetStaffByUsernameRow, error)
	// Use Case 1P: Manage Working Hours
	// Q1P.1: Get Trainer Availability with ID (Get Working Hours)
	GetTrainerAvailability(ctx context.Context, trainerUsername string) ([]TrainingAvailability, error)
	// Use Case 3P: Manage Day-Offs
	// Q3P.1: Get all day-offs for a trainer
	GetTrainerDayOffs(ctx context.Context, trainerUsername sql.NullString) ([]GetTrainerDayOffsRow, error)
	GetTrainingAvaliabilitiesByTrainerUsername(ctx context.Context, trainerUsername string) ([]GetTrainingAvaliabilitiesByTrainerUsernameRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserRole(ctx context.Context, username string) (UsersRole, error)
	// Q3C.6 - อัปเดตจำนวนครั้งที่ใช้ไปแล้ว
	IncrementUsedSessions(ctx context.Context, id int32) error
	// Q5C.2 - อัปเดตจำนวนครั้งที่ใช้ไปแล้วสำหรับ Check-in (Use Case 5C)
	// ใช้ session package ACTIVE ที่ใหม่ที่สุด
	IncrementUsedSessionsByUsername(ctx context.Context, customerUsername sql.NullString) error
	InsertPaymentAccount(ctx context.Context, arg InsertPaymentAccountParams) (sql.Result, error)
	InsertProductDuration(ctx context.Context, arg InsertProductDurationParams) (sql.Result, error)
	InsertProductSession(ctx context.Context, arg InsertProductSessionParams) (sql.Result, error)
	ListAllProducts(ctx context.Context) ([]Product, error)
	// ดึงรายชื่อเทรนเนอร์ทั้งหมดที่ active (สำหรับ dropdown)
	ListAllTrainers(ctx context.Context) ([]ListAllTrainersRow, error)
	ListCustomerDurations(ctx context.Context, arg ListCustomerDurationsParams) ([]ListCustomerDurationsRow, error)
	ListCustomerLogs(ctx context.Context, arg ListCustomerLogsParams) ([]ListCustomerLogsRow, error)
	ListCustomerSessions(ctx context.Context, arg ListCustomerSessionsParams) ([]ListCustomerSessionsRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error)
	ListDurations(ctx context.Context) ([]ListDurationsRow, error)
	ListPaymentAccounts(ctx context.Context, arg ListPaymentAccountsParams) ([]ListPaymentAccountsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListSessions(ctx context.Context) ([]ListSessionsRow, error)
	ListStaffs(ctx context.Context, arg ListStaffsParams) ([]ListStaffsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	NewMembersInRange(ctx context.Context, arg NewMembersInRangeParams) (int64, error)
	RevenueDurations(ctx context.Context, arg RevenueDurationsParams) (int64, error)
	RevenueSessions(ctx context.Context, arg RevenueSessionsParams) (int64, error)
	TopSellingProductsDurations(ctx context.Context, arg TopSellingProductsDurationsParams) ([]TopSellingProductsDurationsRow, error)
	TopSellingProductsSessions(ctx context.Context, arg TopSellingProductsSessionsParams) ([]TopSellingProductsSessionsRow, error)
	UpdateCustomerDurationEditableFields(ctx context.Context, arg UpdateCustomerDurationEditableFieldsParams) error
	UpdateCustomerLogByID(ctx context.Context, arg UpdateCustomerLogByIDParams) (sql.Result, error)
	UpdateCustomerSessionEditableFields(ctx context.Context, arg UpdateCustomerSessionEditableFieldsParams) error
	// อัปเดต users: ไม่มีการเปลี่ยน password
	UpdateCustomerUserNoPassword(ctx context.Context, arg UpdateCustomerUserNoPasswordParams) error
	// อัปเดต users: มีการรีเซ็ตรหัสผ่าน
	UpdateCustomerUserWithPassword(ctx context.Context, arg UpdateCustomerUserWithPasswordParams) error
	// อัปเดตตาราง customers
	UpdateCustomersDetail(ctx context.Context, arg UpdateCustomersDetailParams) error
	UpdatePaymentAccountByID(ctx context.Context, arg UpdatePaymentAccountByIDParams) error
	UpdateProductDuration(ctx context.Context, arg UpdateProductDurationParams) error
	UpdateProductSession(ctx context.Context, arg UpdateProductSessionParams) error
	UpdateStaffNoPassword(ctx context.Context, arg UpdateStaffNoPasswordParams) error
	UpdateStaffWithPassword(ctx context.Context, arg UpdateStaffWithPasswordParams) error
	// Q1P.4: Update Trainer Availability (Edit Working Time)
	UpdateTrainerAvailability(ctx context.Context, arg UpdateTrainerAvailabilityParams) error
	// Q0S.2: Update updated_at when user logs in (track last active time)
	UpdateUserLoginTimestamp(ctx context.Context, username string) error
}

var _ Querier = (*Queries)(nil)
