// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodel

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActiveMembersToday(ctx context.Context) (int64, error)
	CheckGmailExists(ctx context.Context, gmail string) (int64, error)
	CheckPhoneNumberExists(ctx context.Context, phoneNumber string) (int64, error)
	// ตรวจสอบว่ามีนัดซ้อนทับหรือไม่
	CheckScheduleOverlap(ctx context.Context, arg CheckScheduleOverlapParams) (int64, error)
	CheckUsernameExists(ctx context.Context, username string) (int64, error)
	CheckinsToday(ctx context.Context) (int64, error)
	CompletedPTInRange(ctx context.Context, arg CompletedPTInRangeParams) (int64, error)
	// นับจำนวนนัดหมายของเทรนเนอร์ในวันที่กำหนด
	CountAppointmentsOnDate(ctx context.Context, arg CountAppointmentsOnDateParams) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateCustomerDuration(ctx context.Context, arg CreateCustomerDurationParams) error
	CreateCustomerLog(ctx context.Context, arg CreateCustomerLogParams) error
	CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) error
	CreatePaymentAccount(ctx context.Context, arg CreatePaymentAccountParams) error
	CreateTrainingSchedule(ctx context.Context, arg CreateTrainingScheduleParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Q4S.1 แก้ไข: หาเทรนเนอร์ที่ว่างในวันและเวลาที่กำหนด
	FindAvailableTrainers(ctx context.Context, arg FindAvailableTrainersParams) ([]FindAvailableTrainersRow, error)
	GetCustomerDurationById(ctx context.Context, id int32) (CustomerDuration, error)
	GetCustomerDurationsByUsername(ctx context.Context, customerUsername sql.NullString) ([]CustomerDuration, error)
	// Q5S.1: ดึงข้อมูลสินค้าและบัญชีรับชำระเงินเพื่อแสดงหน้าชำระเงิน
	GetPaymentInfoByProductId(ctx context.Context, id int32) (GetPaymentInfoByProductIdRow, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	ListAllProducts(ctx context.Context) ([]Product, error)
	// ดึงรายชื่อเทรนเนอร์ทั้งหมดที่ active (สำหรับ dropdown)
	ListAllTrainers(ctx context.Context) ([]ListAllTrainersRow, error)
	ListDurations(ctx context.Context) ([]ListDurationsRow, error)
	ListSessions(ctx context.Context) ([]ListSessionsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	NewMembersInRange(ctx context.Context, arg NewMembersInRangeParams) (int64, error)
	RevenueDurations(ctx context.Context, arg RevenueDurationsParams) (int64, error)
	RevenueSessions(ctx context.Context, arg RevenueSessionsParams) (int64, error)
	TopSellingProductsDurations(ctx context.Context, arg TopSellingProductsDurationsParams) ([]TopSellingProductsDurationsRow, error)
	TopSellingProductsSessions(ctx context.Context, arg TopSellingProductsSessionsParams) ([]TopSellingProductsSessionsRow, error)
}

var _ Querier = (*Queries)(nil)
