// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const checkGmailExists = `-- name: CheckGmailExists :one
SELECT COUNT(gmail) AS count
FROM users
WHERE gmail = ?
`

func (q *Queries) CheckGmailExists(ctx context.Context, gmail string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkGmailExists, gmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkGmailExistsExceptUsername = `-- name: CheckGmailExistsExceptUsername :one
SELECT COUNT(username) as count
FROM users
WHERE gmail = ?
    AND username != ?
`

type CheckGmailExistsExceptUsernameParams struct {
	Gmail    string `json:"gmail"`
	Username string `json:"username"`
}

func (q *Queries) CheckGmailExistsExceptUsername(ctx context.Context, arg CheckGmailExistsExceptUsernameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkGmailExistsExceptUsername, arg.Gmail, arg.Username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPhoneExists = `-- name: CheckPhoneExists :one
SELECT COUNT(phone_number) AS count
FROM users
WHERE phone_number = ?
`

func (q *Queries) CheckPhoneExists(ctx context.Context, phoneNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPhoneExists, phoneNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPhoneExistsExceptUsername = `-- name: CheckPhoneExistsExceptUsername :one
SELECT COUNT(phone_number) AS count
FROM users
WHERE phone_number = ?
    AND username != ?
`

type CheckPhoneExistsExceptUsernameParams struct {
	PhoneNumber string `json:"phoneNumber"`
	Username    string `json:"username"`
}

func (q *Queries) CheckPhoneExistsExceptUsername(ctx context.Context, arg CheckPhoneExistsExceptUsernameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPhoneExistsExceptUsername, arg.PhoneNumber, arg.Username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaff = `-- name: CreateStaff :exec
INSERT INTO users (
    username, password, role, first_name, last_name,
    gender, date_of_birth, phone_number, gmail, specialty, is_active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE)
`

type CreateStaffParams struct {
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) error {
	_, err := q.db.ExecContext(ctx, createStaff,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.Gmail,
		arg.Specialty,
	)
	return err
}

const deleteCustomerDurationBySales = `-- name: DeleteCustomerDurationBySales :exec
DELETE FROM customer_durations
WHERE sales_username = ?
`

func (q *Queries) DeleteCustomerDurationBySales(ctx context.Context, salesUsername sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerDurationBySales, salesUsername)
	return err
}

const deleteCustomerSessionBySales = `-- name: DeleteCustomerSessionBySales :exec
DELETE FROM customer_sessions
WHERE sales_username = ?
`

func (q *Queries) DeleteCustomerSessionBySales(ctx context.Context, salesUsername sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerSessionBySales, salesUsername)
	return err
}

const deleteCustomerSessionByTrainer = `-- name: DeleteCustomerSessionByTrainer :exec
DELETE FROM customer_sessions
WHERE trainer_username = ?
`

func (q *Queries) DeleteCustomerSessionByTrainer(ctx context.Context, trainerUsername sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerSessionByTrainer, trainerUsername)
	return err
}

const deleteTrainerAvailabilityByTrainer = `-- name: DeleteTrainerAvailabilityByTrainer :exec
DELETE FROM training_availabilities
WHERE trainer_username = ?
`

func (q *Queries) DeleteTrainerAvailabilityByTrainer(ctx context.Context, trainerUsername string) error {
	_, err := q.db.ExecContext(ctx, deleteTrainerAvailabilityByTrainer, trainerUsername)
	return err
}

const deleteTrainingScheduleByTrainer = `-- name: DeleteTrainingScheduleByTrainer :exec
DELETE FROM training_schedules
WHERE trainer_username = ?
`

func (q *Queries) DeleteTrainingScheduleByTrainer(ctx context.Context, trainerUsername sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTrainingScheduleByTrainer, trainerUsername)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
DELETE FROM users
WHERE username = ?
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUsername, username)
	return err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT
    username,
    role,
    first_name,
    last_name,
    gender,
    date_of_birth,
    phone_number,
    gmail,
    specialty,
    is_active
FROM users
WHERE username = ?
`

type GetStaffByUsernameRow struct {
	Username    string         `json:"username"`
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
	IsActive    sql.NullBool   `json:"isActive"`
}

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (GetStaffByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getStaffByUsername, username)
	var i GetStaffByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.DateOfBirth,
		&i.PhoneNumber,
		&i.Gmail,
		&i.Specialty,
		&i.IsActive,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role
FROM users
WHERE username = ?
`

func (q *Queries) GetUserRole(ctx context.Context, username string) (UsersRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, username)
	var role UsersRole
	err := row.Scan(&role)
	return role, err
}

const listStaffs = `-- name: ListStaffs :many
SELECT
    username,
    role,
    first_name,
    last_name,
    gender,
    date_of_birth,
    phone_number,
    gmail,
    specialty,
    is_active
FROM users
WHERE role IN ('TRAINER','SALES','MANAGER','ADMIN')
ORDER BY is_active DESC, role ASC, first_name ASC, last_name ASC
`

type ListStaffsRow struct {
	Username    string         `json:"username"`
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
	IsActive    sql.NullBool   `json:"isActive"`
}

func (q *Queries) ListStaffs(ctx context.Context) ([]ListStaffsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffsRow
	for rows.Next() {
		var i ListStaffsRow
		if err := rows.Scan(
			&i.Username,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.DateOfBirth,
			&i.PhoneNumber,
			&i.Gmail,
			&i.Specialty,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffNoPassword = `-- name: UpdateStaffNoPassword :exec
UPDATE users
SET role         = ?,
    first_name   = ?,
    last_name    = ?,
    gender       = ?,
    date_of_birth= ?,
    phone_number = ?,
    gmail        = ?,
    specialty    = ?,
    is_active    = ?,
    updated_at   = CURRENT_TIMESTAMP
WHERE username = ?
`

type UpdateStaffNoPasswordParams struct {
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
	IsActive    sql.NullBool   `json:"isActive"`
	Username    string         `json:"username"`
}

func (q *Queries) UpdateStaffNoPassword(ctx context.Context, arg UpdateStaffNoPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffNoPassword,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.Gmail,
		arg.Specialty,
		arg.IsActive,
		arg.Username,
	)
	return err
}

const updateStaffWithPassword = `-- name: UpdateStaffWithPassword :exec
UPDATE users
SET password     = ?,
    role         = ?,
    first_name   = ?,
    last_name    = ?,
    gender       = ?,
    date_of_birth= ?,
    phone_number = ?,
    gmail        = ?,
    specialty    = ?,
    is_active    = ?,
    updated_at   = CURRENT_TIMESTAMP
WHERE username = ?
`

type UpdateStaffWithPasswordParams struct {
	Password    string         `json:"password"`
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
	IsActive    sql.NullBool   `json:"isActive"`
	Username    string         `json:"username"`
}

func (q *Queries) UpdateStaffWithPassword(ctx context.Context, arg UpdateStaffWithPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffWithPassword,
		arg.Password,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.Gmail,
		arg.Specialty,
		arg.IsActive,
		arg.Username,
	)
	return err
}
