// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_schedules.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const bookAppointment = `-- name: BookAppointment :exec
INSERT INTO training_schedules (
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, ?, ?, 'APPOINTMENT'
)
`

type BookAppointmentParams struct {
	TrainerUsername  sql.NullString `json:"trainerUsername"`
	CustomerUsername sql.NullString `json:"customerUsername"`
	SessionID        sql.NullInt32  `json:"sessionId"`
	StartTime        time.Time      `json:"startTime"`
	EndTime          time.Time      `json:"endTime"`
}

// Q3C.6 - บันทึกการจองนัด (APPOINTMENT)
func (q *Queries) BookAppointment(ctx context.Context, arg BookAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, bookAppointment,
		arg.TrainerUsername,
		arg.CustomerUsername,
		arg.SessionID,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const checkTimeSlotAvailability = `-- name: CheckTimeSlotAvailability :one
SELECT COUNT(id) AS overlapped_count
FROM training_schedules
WHERE trainer_username = ?
  AND start_time < ?
  AND end_time > ?
`

type CheckTimeSlotAvailabilityParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// Q3C.5 - ตรวจสอบว่าช่วงเวลาที่เลือกยังว่างอยู่จริง
// คืนค่า overlapped_count ถ้าเป็น 0 แสดงว่ายังว่างอยู่
// Logic: ช่วงเวลาซ้อนทับกันเมื่อ start_time < endTime AND end_time > startTime
func (q *Queries) CheckTimeSlotAvailability(ctx context.Context, arg CheckTimeSlotAvailabilityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTimeSlotAvailability, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	var overlapped_count int64
	err := row.Scan(&overlapped_count)
	return overlapped_count, err
}

const createTrainingSchedule = `-- name: CreateTrainingSchedule :exec
INSERT INTO training_schedules (
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateTrainingScheduleParams struct {
	TrainerUsername  sql.NullString                `json:"trainerUsername"`
	CustomerUsername sql.NullString                `json:"customerUsername"`
	SessionID        sql.NullInt32                 `json:"sessionId"`
	StartTime        time.Time                     `json:"startTime"`
	EndTime          time.Time                     `json:"endTime"`
	ScheduleType     TrainingSchedulesScheduleType `json:"scheduleType"`
}

func (q *Queries) CreateTrainingSchedule(ctx context.Context, arg CreateTrainingScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createTrainingSchedule,
		arg.TrainerUsername,
		arg.CustomerUsername,
		arg.SessionID,
		arg.StartTime,
		arg.EndTime,
		arg.ScheduleType,
	)
	return err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM training_schedules
WHERE id = ?
  AND schedule_type = 'APPOINTMENT'
`

// ยกเลิกการจอง - ลบ training_schedule record
// Logic: DELETE FROM training_schedules WHERE id = ? AND schedule_type = 'APPOINTMENT'
// Note: ใช้ id เพียงอย่างเดียว เพราะ id เป็น Primary Key (unique)
// การตรวจสอบ customer_username ทำใน use case layer ก่อนเรียก query นี้
func (q *Queries) DeleteAppointment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const getAppointmentById = `-- name: GetAppointmentById :one
SELECT
  id,
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
FROM training_schedules
WHERE id = ?
  AND schedule_type = 'APPOINTMENT'
`

type GetAppointmentByIdRow struct {
	ID               int32                         `json:"id"`
	TrainerUsername  sql.NullString                `json:"trainerUsername"`
	CustomerUsername sql.NullString                `json:"customerUsername"`
	SessionID        sql.NullInt32                 `json:"sessionId"`
	StartTime        time.Time                     `json:"startTime"`
	EndTime          time.Time                     `json:"endTime"`
	ScheduleType     TrainingSchedulesScheduleType `json:"scheduleType"`
}

// ดึงข้อมูลการจองตาม ID เพื่อตรวจสอบก่อนยกเลิก
func (q *Queries) GetAppointmentById(ctx context.Context, id int32) (GetAppointmentByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentById, id)
	var i GetAppointmentByIdRow
	err := row.Scan(
		&i.ID,
		&i.TrainerUsername,
		&i.CustomerUsername,
		&i.SessionID,
		&i.StartTime,
		&i.EndTime,
		&i.ScheduleType,
	)
	return i, err
}

const getAppointmentSchedules = `-- name: GetAppointmentSchedules :many
SELECT
  start_time,
  end_time,
  customer_username
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND start_time < ?
  AND end_time > ?
`

type GetAppointmentSchedulesParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

type GetAppointmentSchedulesRow struct {
	StartTime        time.Time      `json:"startTime"`
	EndTime          time.Time      `json:"endTime"`
	CustomerUsername sql.NullString `json:"customerUsername"`
}

// Q3C.3b - ดึงนัดที่ถูกจองแล้ว (APPOINTMENT)
func (q *Queries) GetAppointmentSchedules(ctx context.Context, arg GetAppointmentSchedulesParams) ([]GetAppointmentSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentSchedules, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentSchedulesRow
	for rows.Next() {
		var i GetAppointmentSchedulesRow
		if err := rows.Scan(&i.StartTime, &i.EndTime, &i.CustomerUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDayOffSchedules = `-- name: GetDayOffSchedules :many
SELECT
  start_time,
  end_time
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'DAY_OFF'
  AND start_time < ?
  AND end_time > ?
`

type GetDayOffSchedulesParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

type GetDayOffSchedulesRow struct {
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

// Q3C.3a - ดึงวันหยุดหรือช่วงเวลาที่ไม่รับนัด (DAY_OFF)
func (q *Queries) GetDayOffSchedules(ctx context.Context, arg GetDayOffSchedulesParams) ([]GetDayOffSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDayOffSchedules, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDayOffSchedulesRow
	for rows.Next() {
		var i GetDayOffSchedulesRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
