// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_avaliabilities.sql

package dbmodel

import (
	"context"
	"time"
)

const getTrainingAvaliabilitiesByTrainerUsername = `-- name: GetTrainingAvaliabilitiesByTrainerUsername :many
SELECT 
  trainer_username,
  day_of_week,
  start_time,
  end_time
FROM training_availabilities
WHERE trainer_username = ?
ORDER BY day_of_week, start_time ASC
`

type GetTrainingAvaliabilitiesByTrainerUsernameRow struct {
	TrainerUsername string                          `json:"trainerUsername"`
	DayOfWeek       TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	StartTime       time.Time                       `json:"startTime"`
	EndTime         time.Time                       `json:"endTime"`
}

func (q *Queries) GetTrainingAvaliabilitiesByTrainerUsername(ctx context.Context, trainerUsername string) ([]GetTrainingAvaliabilitiesByTrainerUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainingAvaliabilitiesByTrainerUsername, trainerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingAvaliabilitiesByTrainerUsernameRow
	for rows.Next() {
		var i GetTrainingAvaliabilitiesByTrainerUsernameRow
		if err := rows.Scan(
			&i.TrainerUsername,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
