// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_schedules.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const bookAppointment = `-- name: BookAppointment :exec
INSERT INTO training_schedules (
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, ?, ?, 'APPOINTMENT'
)
`

type BookAppointmentParams struct {
	TrainerUsername  sql.NullString `json:"trainerUsername"`
	CustomerUsername sql.NullString `json:"customerUsername"`
	SessionID        sql.NullInt32  `json:"sessionId"`
	StartTime        time.Time      `json:"startTime"`
	EndTime          time.Time      `json:"endTime"`
}

// Q2C.7 - บันทึกการจองนัด (APPOINTMENT)
func (q *Queries) BookAppointment(ctx context.Context, arg BookAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, bookAppointment,
		arg.TrainerUsername,
		arg.CustomerUsername,
		arg.SessionID,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const checkDayOffAppointmentOverlap = `-- name: CheckDayOffAppointmentOverlap :one
SELECT COUNT(id) AS overlapped_count
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND start_time < ?
  AND end_time > ?
`

type CheckDayOffAppointmentOverlapParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// Q6C.5: Check if day-off overlaps with existing appointments
func (q *Queries) CheckDayOffAppointmentOverlap(ctx context.Context, arg CheckDayOffAppointmentOverlapParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDayOffAppointmentOverlap, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	var overlapped_count int64
	err := row.Scan(&overlapped_count)
	return overlapped_count, err
}

const checkDayOffDuplicate = `-- name: CheckDayOffDuplicate :one
SELECT COUNT(id) AS duplicate_count
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'DAY_OFF'
  AND DATE(start_time) = ?
`

type CheckDayOffDuplicateParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
}

// Q2P.2: Check if day-off already exists for the same date
func (q *Queries) CheckDayOffDuplicate(ctx context.Context, arg CheckDayOffDuplicateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDayOffDuplicate, arg.TrainerUsername, arg.StartTime)
	var duplicate_count int64
	err := row.Scan(&duplicate_count)
	return duplicate_count, err
}

const checkTimeSlotAvailability = `-- name: CheckTimeSlotAvailability :one
SELECT COUNT(id) AS overlapped_count
FROM training_schedules
WHERE trainer_username = ?
  AND start_time < ?
  AND end_time > ?
`

type CheckTimeSlotAvailabilityParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// Q2C.6 - ตรวจสอบว่าช่วงเวลาที่เลือกยังว่างอยู่จริง
// คืนค่า overlapped_count ถ้าเป็น 0 แสดงว่ายังว่างอยู่
// Logic: ช่วงเวลาซ้อนทับกันเมื่อ start_time < endTime AND end_time > startTime
func (q *Queries) CheckTimeSlotAvailability(ctx context.Context, arg CheckTimeSlotAvailabilityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTimeSlotAvailability, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	var overlapped_count int64
	err := row.Scan(&overlapped_count)
	return overlapped_count, err
}

const createDayOff = `-- name: CreateDayOff :exec
INSERT INTO training_schedules (
  trainer_username,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, 'DAY_OFF'
)
`

type CreateDayOffParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// Q3P.4: Create day-off
func (q *Queries) CreateDayOff(ctx context.Context, arg CreateDayOffParams) error {
	_, err := q.db.ExecContext(ctx, createDayOff, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	return err
}

const createTrainingSchedule = `-- name: CreateTrainingSchedule :exec
INSERT INTO training_schedules (
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateTrainingScheduleParams struct {
	TrainerUsername  sql.NullString                `json:"trainerUsername"`
	CustomerUsername sql.NullString                `json:"customerUsername"`
	SessionID        sql.NullInt32                 `json:"sessionId"`
	StartTime        time.Time                     `json:"startTime"`
	EndTime          time.Time                     `json:"endTime"`
	ScheduleType     TrainingSchedulesScheduleType `json:"scheduleType"`
}

func (q *Queries) CreateTrainingSchedule(ctx context.Context, arg CreateTrainingScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createTrainingSchedule,
		arg.TrainerUsername,
		arg.CustomerUsername,
		arg.SessionID,
		arg.StartTime,
		arg.EndTime,
		arg.ScheduleType,
	)
	return err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM training_schedules
WHERE id = ?
  AND schedule_type = 'APPOINTMENT'
`

// ยกเลิกการจอง - ลบ training_schedule record
// Logic: DELETE FROM training_schedules WHERE id = ? AND schedule_type = 'APPOINTMENT'
// Note: ใช้ id เพียงอย่างเดียว เพราะ id เป็น Primary Key (unique)
// การตรวจสอบ customer_username ทำใน use case layer ก่อนเรียก query นี้
func (q *Queries) DeleteAppointment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const deleteDayOff = `-- name: DeleteDayOff :exec
DELETE FROM training_schedules
WHERE id = ?
  AND schedule_type = 'DAY_OFF'
`

// Q3P.5: Delete day-off
func (q *Queries) DeleteDayOff(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDayOff, id)
	return err
}

const getAppointmentById = `-- name: GetAppointmentById :one
SELECT
  id,
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
FROM training_schedules
WHERE id = ?
  AND schedule_type = 'APPOINTMENT'
`

type GetAppointmentByIdRow struct {
	ID               int32                         `json:"id"`
	TrainerUsername  sql.NullString                `json:"trainerUsername"`
	CustomerUsername sql.NullString                `json:"customerUsername"`
	SessionID        sql.NullInt32                 `json:"sessionId"`
	StartTime        time.Time                     `json:"startTime"`
	EndTime          time.Time                     `json:"endTime"`
	ScheduleType     TrainingSchedulesScheduleType `json:"scheduleType"`
}

// ดึงข้อมูลการจองตาม ID เพื่อตรวจสอบก่อนยกเลิก
func (q *Queries) GetAppointmentById(ctx context.Context, id int32) (GetAppointmentByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentById, id)
	var i GetAppointmentByIdRow
	err := row.Scan(
		&i.ID,
		&i.TrainerUsername,
		&i.CustomerUsername,
		&i.SessionID,
		&i.StartTime,
		&i.EndTime,
		&i.ScheduleType,
	)
	return i, err
}

const getAppointmentSchedules = `-- name: GetAppointmentSchedules :many
SELECT
  id,
  start_time,
  end_time,
  customer_username
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND start_time < ?
  AND end_time > ?
`

type GetAppointmentSchedulesParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

type GetAppointmentSchedulesRow struct {
	ID               int32          `json:"id"`
	StartTime        time.Time      `json:"startTime"`
	EndTime          time.Time      `json:"endTime"`
	CustomerUsername sql.NullString `json:"customerUsername"`
}

// Q3C.3b - ดึงนัดที่ถูกจองแล้ว (APPOINTMENT)
func (q *Queries) GetAppointmentSchedules(ctx context.Context, arg GetAppointmentSchedulesParams) ([]GetAppointmentSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentSchedules, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentSchedulesRow
	for rows.Next() {
		var i GetAppointmentSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.CustomerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerScheduleForToday = `-- name: GetCustomerScheduleForToday :one
SELECT 
  id,
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time
FROM training_schedules
WHERE customer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND DATE(start_time) = CURDATE()
  AND start_time <= NOW()
  AND end_time >= NOW()
ORDER BY start_time DESC
LIMIT 1
`

type GetCustomerScheduleForTodayRow struct {
	ID               int32          `json:"id"`
	TrainerUsername  sql.NullString `json:"trainerUsername"`
	CustomerUsername sql.NullString `json:"customerUsername"`
	SessionID        sql.NullInt32  `json:"sessionId"`
	StartTime        time.Time      `json:"startTime"`
	EndTime          time.Time      `json:"endTime"`
}

// Find customer's schedule for today (for check-in flow)
func (q *Queries) GetCustomerScheduleForToday(ctx context.Context, customerUsername sql.NullString) (GetCustomerScheduleForTodayRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerScheduleForToday, customerUsername)
	var i GetCustomerScheduleForTodayRow
	err := row.Scan(
		&i.ID,
		&i.TrainerUsername,
		&i.CustomerUsername,
		&i.SessionID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const getDayOffSchedules = `-- name: GetDayOffSchedules :many
SELECT
  start_time,
  end_time
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'DAY_OFF'
  AND start_time < ?
  AND end_time > ?
`

type GetDayOffSchedulesParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

type GetDayOffSchedulesRow struct {
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

// Q3C.3a - ดึงวันหยุดหรือช่วงเวลาที่ไม่รับนัด (DAY_OFF)
func (q *Queries) GetDayOffSchedules(ctx context.Context, arg GetDayOffSchedulesParams) ([]GetDayOffSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDayOffSchedules, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDayOffSchedulesRow
	for rows.Next() {
		var i GetDayOffSchedulesRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainerAppointmentsWithPendingCheckIns = `-- name: GetTrainerAppointmentsWithPendingCheckIns :many
SELECT 
  ts.id AS schedule_id,
  ts.customer_username,
  u.first_name AS customer_first_name,
  u.last_name AS customer_last_name,
  ts.start_time,
  ts.end_time,
  ts.session_id,
  cs.total_sessions,
  cs.used_sessions,
  COALESCE(cl.status, 'NONE') AS checkin_status,
  cl.id AS checkin_log_id,
  cl.created_at AS checkin_time
FROM training_schedules ts
JOIN users u ON u.username = ts.customer_username
LEFT JOIN customer_sessions cs ON cs.id = ts.session_id
LEFT JOIN customer_logs cl ON cl.schedule_id = ts.id 
  AND cl.log_type = 'CHECK_IN' 
  AND cl.status = 'PENDING'
WHERE ts.trainer_username = ?
  AND ts.schedule_type = 'APPOINTMENT'
  AND DATE(ts.start_time) >= CURDATE()
ORDER BY ts.start_time ASC
`

type GetTrainerAppointmentsWithPendingCheckInsRow struct {
	ScheduleID        int32              `json:"scheduleId"`
	CustomerUsername  sql.NullString     `json:"customerUsername"`
	CustomerFirstName string             `json:"customerFirstName"`
	CustomerLastName  string             `json:"customerLastName"`
	StartTime         time.Time          `json:"startTime"`
	EndTime           time.Time          `json:"endTime"`
	SessionID         sql.NullInt32      `json:"sessionId"`
	TotalSessions     sql.NullInt32      `json:"totalSessions"`
	UsedSessions      sql.NullInt32      `json:"usedSessions"`
	CheckinStatus     CustomerLogsStatus `json:"checkinStatus"`
	CheckinLogID      sql.NullInt32      `json:"checkinLogId"`
	CheckinTime       sql.NullTime       `json:"checkinTime"`
}

// Get trainer's appointments with pending check-ins (for trainer calendar)
func (q *Queries) GetTrainerAppointmentsWithPendingCheckIns(ctx context.Context, trainerUsername sql.NullString) ([]GetTrainerAppointmentsWithPendingCheckInsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainerAppointmentsWithPendingCheckIns, trainerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainerAppointmentsWithPendingCheckInsRow
	for rows.Next() {
		var i GetTrainerAppointmentsWithPendingCheckInsRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.CustomerUsername,
			&i.CustomerFirstName,
			&i.CustomerLastName,
			&i.StartTime,
			&i.EndTime,
			&i.SessionID,
			&i.TotalSessions,
			&i.UsedSessions,
			&i.CheckinStatus,
			&i.CheckinLogID,
			&i.CheckinTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainerDayOffs = `-- name: GetTrainerDayOffs :many

SELECT
  id,
  trainer_username,
  start_time,
  end_time
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'DAY_OFF'
ORDER BY start_time DESC
`

type GetTrainerDayOffsRow struct {
	ID              int32          `json:"id"`
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// Use Case 3P: Manage Day-Offs
// Q2P.1: Get all day-offs for a trainer
func (q *Queries) GetTrainerDayOffs(ctx context.Context, trainerUsername sql.NullString) ([]GetTrainerDayOffsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainerDayOffs, trainerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainerDayOffsRow
	for rows.Next() {
		var i GetTrainerDayOffsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainerUsername,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
