// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainers.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const checkScheduleOverlap = `-- name: CheckScheduleOverlap :one
SELECT COUNT(id) as count
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND start_time < ?
  AND end_time > ?
`

type CheckScheduleOverlapParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	StartTime       time.Time      `json:"startTime"`
	EndTime         time.Time      `json:"endTime"`
}

// ตรวจสอบว่ามีนัดซ้อนทับหรือไม่
func (q *Queries) CheckScheduleOverlap(ctx context.Context, arg CheckScheduleOverlapParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkScheduleOverlap, arg.TrainerUsername, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppointmentsOnDate = `-- name: CountAppointmentsOnDate :one
SELECT COUNT(id) as count
FROM training_schedules
WHERE trainer_username = ?
  AND schedule_type = 'APPOINTMENT'
  AND DATE(start_time) = DATE(?)
`

type CountAppointmentsOnDateParams struct {
	TrainerUsername sql.NullString `json:"trainerUsername"`
	DATE            time.Time      `json:"DATE"`
}

// นับจำนวนนัดหมายของเทรนเนอร์ในวันที่กำหนด
func (q *Queries) CountAppointmentsOnDate(ctx context.Context, arg CountAppointmentsOnDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppointmentsOnDate, arg.TrainerUsername, arg.DATE)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAvailableTrainers = `-- name: FindAvailableTrainers :many
SELECT 
  u.username,
  u.first_name,
  u.last_name,
  u.created_at
FROM users u
JOIN training_availabilities ta 
  ON ta.trainer_username = u.username
WHERE 
  u.role = 'TRAINER'
  AND u.is_active = TRUE
  AND ta.day_of_week = ?
  AND TIME(?) >= ta.start_time
  AND TIME(?) <= ta.end_time
ORDER BY u.created_at ASC
`

type FindAvailableTrainersParams struct {
	DayOfWeek TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	TIME      time.Time                       `json:"TIME"`
	TIME_2    time.Time                       `json:"TIME2"`
}

type FindAvailableTrainersRow struct {
	Username  string    `json:"username"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
}

// Q4S.1 แก้ไข: หาเทรนเนอร์ที่ว่างในวันและเวลาที่กำหนด
func (q *Queries) FindAvailableTrainers(ctx context.Context, arg FindAvailableTrainersParams) ([]FindAvailableTrainersRow, error) {
	rows, err := q.db.QueryContext(ctx, findAvailableTrainers, arg.DayOfWeek, arg.TIME, arg.TIME_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAvailableTrainersRow
	for rows.Next() {
		var i FindAvailableTrainersRow
		if err := rows.Scan(
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTrainers = `-- name: ListAllTrainers :many
SELECT 
  username,
  first_name,
  last_name
FROM users
WHERE role = 'TRAINER'
  AND is_active = TRUE
ORDER BY first_name, last_name, username
`

type ListAllTrainersRow struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

// ดึงรายชื่อเทรนเนอร์ทั้งหมดที่ active (สำหรับ dropdown)
func (q *Queries) ListAllTrainers(ctx context.Context) ([]ListAllTrainersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTrainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTrainersRow
	for rows.Next() {
		var i ListAllTrainersRow
		if err := rows.Scan(&i.Username, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
