// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_avaliabilities.sql

package dbmodel

import (
	"context"
	"time"
)

const checkTimeOverlap = `-- name: CheckTimeOverlap :one
SELECT COUNT(id) AS overlapped_count
FROM training_availabilities
WHERE trainer_username = ?
  AND day_of_week = ?
  AND (
    (TIME(?) < TIME(end_time) AND TIME(?) > TIME(start_time))
  )
`

type CheckTimeOverlapParams struct {
	TrainerUsername string                          `json:"trainerUsername"`
	DayOfWeek       TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	TIME            time.Time                       `json:"TIME"`
	TIME_2          time.Time                       `json:"TIME2"`
}

// Q1P.2: Check Time Overlap (Validation before adding)
// Note: Since start_time and end_time are TIMESTAMP, we compare TIME portions only
// We check if the new time slot overlaps with existing ones on the same day
func (q *Queries) CheckTimeOverlap(ctx context.Context, arg CheckTimeOverlapParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTimeOverlap,
		arg.TrainerUsername,
		arg.DayOfWeek,
		arg.TIME,
		arg.TIME_2,
	)
	var overlapped_count int64
	err := row.Scan(&overlapped_count)
	return overlapped_count, err
}

const createTrainerAvailability = `-- name: CreateTrainerAvailability :exec
INSERT INTO training_availabilities (
  trainer_username,
  day_of_week,
  start_time,
  end_time
) VALUES (?, ?, ?, ?)
`

type CreateTrainerAvailabilityParams struct {
	TrainerUsername string                          `json:"trainerUsername"`
	DayOfWeek       TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	StartTime       time.Time                       `json:"startTime"`
	EndTime         time.Time                       `json:"endTime"`
}

// Q1P.3: Create Trainer Availability (Add Working Time)
func (q *Queries) CreateTrainerAvailability(ctx context.Context, arg CreateTrainerAvailabilityParams) error {
	_, err := q.db.ExecContext(ctx, createTrainerAvailability,
		arg.TrainerUsername,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const deleteTrainerAvailability = `-- name: DeleteTrainerAvailability :exec
DELETE FROM training_availabilities
WHERE id = ?
`

// Q1P.5: Delete Trainer Availability (Remove Working Time)
func (q *Queries) DeleteTrainerAvailability(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTrainerAvailability, id)
	return err
}

const getTrainerAvailability = `-- name: GetTrainerAvailability :many

SELECT
  id,
  trainer_username,
  day_of_week,
  start_time,
  end_time
FROM training_availabilities
WHERE trainer_username = ?
ORDER BY FIELD(day_of_week, 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'),
         start_time ASC
`

// Use Case 1P: Manage Working Hours
// Q1P.1: Get Trainer Availability with ID (Get Working Hours)
func (q *Queries) GetTrainerAvailability(ctx context.Context, trainerUsername string) ([]TrainingAvailability, error) {
	rows, err := q.db.QueryContext(ctx, getTrainerAvailability, trainerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingAvailability
	for rows.Next() {
		var i TrainingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TrainerUsername,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainingAvaliabilitiesByTrainerUsername = `-- name: GetTrainingAvaliabilitiesByTrainerUsername :many
SELECT 
  trainer_username,
  day_of_week,
  start_time,
  end_time
FROM training_availabilities
WHERE trainer_username = ?
ORDER BY day_of_week, start_time ASC
`

type GetTrainingAvaliabilitiesByTrainerUsernameRow struct {
	TrainerUsername string                          `json:"trainerUsername"`
	DayOfWeek       TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	StartTime       time.Time                       `json:"startTime"`
	EndTime         time.Time                       `json:"endTime"`
}

func (q *Queries) GetTrainingAvaliabilitiesByTrainerUsername(ctx context.Context, trainerUsername string) ([]GetTrainingAvaliabilitiesByTrainerUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainingAvaliabilitiesByTrainerUsername, trainerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingAvaliabilitiesByTrainerUsernameRow
	for rows.Next() {
		var i GetTrainingAvaliabilitiesByTrainerUsernameRow
		if err := rows.Scan(
			&i.TrainerUsername,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainerAvailability = `-- name: UpdateTrainerAvailability :exec
UPDATE training_availabilities
SET
  day_of_week = ?,
  start_time = ?,
  end_time = ?
WHERE id = ?
`

type UpdateTrainerAvailabilityParams struct {
	DayOfWeek TrainingAvailabilitiesDayOfWeek `json:"dayOfWeek"`
	StartTime time.Time                       `json:"startTime"`
	EndTime   time.Time                       `json:"endTime"`
	ID        int32                           `json:"id"`
}

// Q1P.4: Update Trainer Availability (Edit Working Time)
func (q *Queries) UpdateTrainerAvailability(ctx context.Context, arg UpdateTrainerAvailabilityParams) error {
	_, err := q.db.ExecContext(ctx, updateTrainerAvailability,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	return err
}
