// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_schedules.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const createTrainingSchedule = `-- name: CreateTrainingSchedule :exec
INSERT INTO training_schedules (
  trainer_username,
  customer_username,
  session_id,
  start_time,
  end_time,
  schedule_type
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateTrainingScheduleParams struct {
	TrainerUsername  sql.NullString                `json:"trainerUsername"`
	CustomerUsername sql.NullString                `json:"customerUsername"`
	SessionID        sql.NullInt32                 `json:"sessionId"`
	StartTime        time.Time                     `json:"startTime"`
	EndTime          time.Time                     `json:"endTime"`
	ScheduleType     TrainingSchedulesScheduleType `json:"scheduleType"`
}

func (q *Queries) CreateTrainingSchedule(ctx context.Context, arg CreateTrainingScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createTrainingSchedule,
		arg.TrainerUsername,
		arg.CustomerUsername,
		arg.SessionID,
		arg.StartTime,
		arg.EndTime,
		arg.ScheduleType,
	)
	return err
}
