// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodel

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password, email, role, first_name, last_name, gender, date_of_birth, phone_number, gmail, specialty, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

func (q *Queries) CreateUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUser)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password, role, first_name, last_name FROM users WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      UsersRole `json:"role"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
}

func (q *Queries) GetUserByUsername(ctx context.Context) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username, email, created_at
FROM users
ORDER BY username
`

type ListUsersRow struct {
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Username, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
