// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodel

import (
	"context"
	"database/sql"
	"time"
)

const checkGmailExistsUser = `-- name: CheckGmailExistsUser :one
SELECT COUNT(gmail) as count
FROM users
WHERE gmail = ?
`

func (q *Queries) CheckGmailExistsUser(ctx context.Context, gmail string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkGmailExistsUser, gmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPhoneNumberExistsUser = `-- name: CheckPhoneNumberExistsUser :one
SELECT COUNT(phone_number) as count
FROM users
WHERE phone_number = ?
`

func (q *Queries) CheckPhoneNumberExistsUser(ctx context.Context, phoneNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPhoneNumberExistsUser, phoneNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT COUNT(username) as count
FROM users
WHERE username = ?
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password, role, first_name, last_name, gender, date_of_birth, phone_number, gmail, specialty, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Role        UsersRole      `json:"role"`
	FirstName   string         `json:"firstName"`
	LastName    string         `json:"lastName"`
	Gender      UsersGender    `json:"gender"`
	DateOfBirth time.Time      `json:"dateOfBirth"`
	PhoneNumber string         `json:"phoneNumber"`
	Gmail       string         `json:"gmail"`
	Specialty   sql.NullString `json:"specialty"`
	IsActive    sql.NullBool   `json:"isActive"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.Gmail,
		arg.Specialty,
		arg.IsActive,
	)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password, role, first_name, last_name
FROM users
WHERE username = ?
LIMIT 1
`

type GetUserByUsernameRow struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      UsersRole `json:"role"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username, gmail, created_at
FROM users
ORDER BY username
`

type ListUsersRow struct {
	Username  string    `json:"username"`
	Gmail     string    `json:"gmail"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Username, &i.Gmail, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLoginTimestamp = `-- name: UpdateUserLoginTimestamp :exec
UPDATE users
SET updated_at = CURRENT_TIMESTAMP
WHERE username = ?
`

// Q0S.2: Update updated_at when user logs in (track last active time)
func (q *Queries) UpdateUserLoginTimestamp(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, updateUserLoginTimestamp, username)
	return err
}
