// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/WaritDev/private-fitness-backend/config"
	"github.com/WaritDev/private-fitness-backend/domain/usecases"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/repositories/sql"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/rest"
	"github.com/WaritDev/private-fitness-backend/internal/infrastructure/db"
)

// Injectors from wire.go:

func InitializeHandler() *rest.Handler {
	context := ProvideContext()
	configConfig := config.ProvideConfig()
	sqlDB := db.ProvideMariaDB(context, configConfig)
	queries := db.ProvideQueries(sqlDB)
	userRepository := sql.ProvideUserRepository(queries, sqlDB)
	userUseCase := usecases.ProvideUserUseCase(userRepository)
	userHandler := rest.ProvideUserHandler(userUseCase)
	managerDashboardRepository := sql.ProvideManagerDashboardRepository(sqlDB)
	managerDashboardUsecase := usecases.ProvideManagerDashboardUsecase(managerDashboardRepository)
	managerDashboardHandler := rest.ProvideManagerDashboardHandler(managerDashboardUsecase)
	authRepository := sql.ProvideAuthRepository()
	authUseCase := usecases.ProvideAuthUseCase(authRepository, userRepository)
	authHandler := rest.ProvideAuthHandler(authUseCase)
	productRepository := sql.ProvideProductRepository(queries)
	productUseCase := usecases.ProvideProductUseCase(productRepository)
	productHandler := rest.ProvideProductHandler(productUseCase)
	trainerRepository := sql.ProvideTrainerRepository(queries)
	sessionUseCase := usecases.ProvideSessionUseCase(trainerRepository)
	trainerHandler := rest.ProvideTrainerHandler(sessionUseCase)
	paymentAccountRepository := sql.ProvidePaymentAccountRepository(queries)
	paymentUseCase := usecases.ProvidePaymentUseCase(paymentAccountRepository)
	paymentHandler := rest.ProvidePaymentHandler(paymentUseCase)
	staffRepository := sql.ProvideStaffRepository(sqlDB)
	staffUsecase := usecases.ProvideStaffUsecase(staffRepository)
	staffHandler := rest.ProvideStaffHandler(staffUsecase)
	customerRepository := sql.ProvideCustomerRepository(sqlDB)
	customerUsecase := usecases.ProvideCustomerUsecase(customerRepository)
	customerHandler := rest.ProvideCustomerHandler(customerUsecase)
	customerSessionRepository := sql.ProvideCustomerSessionRepository(queries, sqlDB)
	customerSessionUseCase := usecases.ProvideCustomerSessionUseCase(customerSessionRepository, userRepository, sqlDB)
	customerSessionHandler := rest.ProvideCustomerSessionHandler(customerSessionUseCase)
	customerDurationRepository := sql.ProvideCustomerDurationRepository(queries, sqlDB)
	customerDurationUseCase := usecases.ProvideCustomerDurationUseCase(customerDurationRepository, productRepository, userRepository, sqlDB)
	customerDurationHandler := rest.ProvideCustomerDurationHandler(customerDurationUseCase, authUseCase)
	trainingScheduleRepository := sql.ProvideTrainingScheduleRepository(queries)
	customerLogRepository := sql.ProvideCustomerLogRepository(queries)
	bookingUseCase := usecases.ProvideBookingUseCase(trainingScheduleRepository, customerSessionRepository, customerLogRepository, sqlDB)
	bookingHandler := rest.ProvideBookingHandler(bookingUseCase)
	memberUseCase := usecases.ProvideMemberUseCase(customerLogRepository, customerSessionRepository, userRepository, authRepository, sqlDB)
	memberHandler := rest.ProvideMemberHandler(memberUseCase, authUseCase)
	customerLogUsecase := usecases.ProvideCustomerLogUsecase(customerLogRepository)
	customerLogHandler := rest.ProvideCustomerLogHandler(customerLogUsecase)
	handler := rest.ProvideHandler(userHandler, managerDashboardHandler, authHandler, productHandler, trainerHandler, paymentHandler, staffHandler, customerHandler, customerSessionHandler, customerDurationHandler, bookingHandler, memberHandler, customerLogHandler)
	return handler
}
