// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/WaritDev/private-fitness-backend/config"
	"github.com/WaritDev/private-fitness-backend/domain/usecases"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/repositories/psql"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/rest"
	"github.com/WaritDev/private-fitness-backend/internal/infrastructure/db"
)

// Injectors from wire.go:

func InitializeHandler() *rest.Handler {
	context := ProvideContext()
	configConfig := config.ProvideConfig()
	pool := db.ProvidePgxPool(context, configConfig)
	queries := db.ProvideQueries(pool)
	userRepository := psql.ProvideUserRepository(queries)
	userUseCase := usecases.ProvideUserUseCase(userRepository)
	userHandler := rest.ProvideUserHandler(userUseCase)
	handler := rest.ProvideHandler(userHandler)
	return handler
}
