// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/WaritDev/private-fitness-backend/config"
	"github.com/WaritDev/private-fitness-backend/domain/services"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/repositories/sql"
	"github.com/WaritDev/private-fitness-backend/internal/adapters/rest/controller"
	"github.com/WaritDev/private-fitness-backend/internal/infrastructure/db"
)

// Injectors from wire.go:

func InitializeController() *controller.Controller {
	context := ProvideContext()
	configConfig := config.ProvideConfig()
	sqlDB := db.ProvideMariaDB(context, configConfig)
	queries := db.ProvideQueries(sqlDB)
	userRepository := sql.ProvideUserRepository(queries, sqlDB)
	userService := services.ProvideUserService(userRepository)
	userController := controller.ProvideUserController(userService)
	managerDashboardRepository := sql.ProvideManagerDashboardRepository(sqlDB)
	managerDashboardService := services.ProvideManagerDashboardService(managerDashboardRepository)
	managerDashboardController := controller.ProvideManagerDashboardController(managerDashboardService)
	authRepository := sql.ProvideAuthRepository()
	authService := services.ProvideAuthService(authRepository, userRepository)
	authController := controller.ProvideAuthController(authService)
	productRepository := sql.ProvideProductRepository(queries)
	productService := services.ProvideProductService(productRepository)
	productController := controller.ProvideProductController(productService)
	trainerRepository := sql.ProvideTrainerRepository(queries)
	sessionService := services.ProvideSessionService(trainerRepository)
	trainingScheduleRepository := sql.ProvideTrainingScheduleRepository(queries)
	customerLogRepository := sql.ProvideCustomerLogRepository(queries)
	customerSessionRepository := sql.ProvideCustomerSessionRepository(queries, sqlDB)
	trainerService := services.ProvideTrainerService(trainerRepository, trainingScheduleRepository, customerLogRepository, customerSessionRepository, sqlDB)
	trainerController := controller.ProvideTrainerController(sessionService, trainerService)
	paymentAccountRepository := sql.ProvidePaymentAccountRepository(queries)
	paymentService := services.ProvidePaymentService(paymentAccountRepository, configConfig)
	paymentController := controller.ProvidePaymentController(paymentService)
	staffRepository := sql.ProvideStaffRepository(sqlDB)
	staffService := services.ProvideStaffService(staffRepository)
	staffController := controller.ProvideStaffController(staffService)
	customerRepository := sql.ProvideCustomerRepository(sqlDB)
	customerService := services.ProvideCustomerService(customerRepository)
	customerController := controller.ProvideCustomerController(customerService)
	customerSessionService := services.ProvideCustomerSessionService(customerSessionRepository, userRepository, sqlDB)
	customerSessionController := controller.ProvideCustomerSessionController(customerSessionService, authService)
	customerDurationRepository := sql.ProvideCustomerDurationRepository(queries, sqlDB)
	customerDurationService := services.ProvideCustomerDurationService(customerDurationRepository, productRepository, userRepository, sqlDB)
	customerDurationController := controller.ProvideCustomerDurationController(customerDurationService, authService)
	bookingService := services.ProvideBookingService(trainingScheduleRepository, customerSessionRepository, customerLogRepository, sqlDB)
	bookingController := controller.ProvideBookingController(bookingService)
	memberService := services.ProvideMemberService(customerLogRepository, customerSessionRepository, trainingScheduleRepository, userRepository, authRepository, sqlDB)
	memberController := controller.ProvideMemberController(memberService, authService)
	customerLogService := services.ProvideCustomerLogService(customerLogRepository)
	customerLogController := controller.ProvideCustomerLogController(customerLogService)
	controllerController := controller.ProvideController(userController, managerDashboardController, authController, productController, trainerController, paymentController, staffController, customerController, customerSessionController, customerDurationController, bookingController, memberController, customerLogController)
	return controllerController
}
